Repository qbittorrent/qBittorrent, pull requests merged in 2018-09, with the labels that each got.

#9436 Don't disable DHT when using force proxy
  src/gui/optionsdialog.cpp
  src/webui/www/private/preferences_content.html
Labels: GUI, WebUI

#9444 Fix GUI scaling issue on Linux
  src/app/main.cpp
Labels: GUI, Linux

#9387 Minor WebUI visual changes
  src/webui/www/private/css/style.css
  src/webui/www/private/filters.html
  src/webui/www/private/preferences_content.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/mocha-init.js
Labels: WebUI

#9383 Decrease probability of missing important alerts
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrenthandle.cpp
Labels: Core

#9461 Show "N/A" if there is no scrape response
  src/base/bittorrent/torrentinfo.cpp
  src/base/bittorrent/torrentinfo.h
  src/base/net/downloadmanager.cpp
  src/base/net/private/geoipdatabase.cpp
  src/gui/addnewtorrentdialog.cpp
  src/gui/categoryfiltermodel.cpp
  src/gui/cookiesmodel.cpp
  src/gui/guiiconprovider.h
  src/gui/mainwindow.cpp
  src/gui/properties/peerlistdelegate.h
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/peerlistwidget.h
  src/gui/properties/trackerlistwidget.cpp
  src/gui/scanfoldersdelegate.cpp
  src/gui/search/pluginselectdialog.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/tagfiltermodel.cpp
  src/gui/tagfiltermodel.h
  src/gui/torrentcontentfiltermodel.h
  src/gui/torrentcontentmodel.cpp
  src/gui/torrentcontentmodel.h
  src/gui/torrentcontentmodelfolder.cpp
  src/gui/torrentcontentmodelfolder.h
  src/gui/torrentcreatordialog.h
  src/gui/transferlistdelegate.cpp
  src/gui/transferlistfilterswidget.h
  src/gui/transferlistmodel.cpp
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
Labels: GUI

#9406 Preselect name without extension when renaming files
  src/gui/addnewtorrentdialog.cpp
  src/gui/autoexpandabledialog.cpp
  src/gui/autoexpandabledialog.h
  src/gui/properties/propertieswidget.cpp
Labels: GUI

#9483 Save state change from queued to paused
  src/base/bittorrent/torrenthandle.cpp
Labels: Hotfix

#9228 Add save path and category editing to WebUI
  src/base/bittorrent/torrenthandle.cpp
  src/webui/api/synccontroller.cpp
  src/webui/api/torrentscontroller.cpp
  src/webui/api/torrentscontroller.h
  src/webui/extra_translations.h
  src/webui/www/private/filters.html
  src/webui/www/private/index.html
  src/webui/www/private/newcategory.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/mocha-init.js
Labels: WebAPI, WebUI

#9482 Fix typo in variable name
  src/base/bittorrent/torrentinfo.cpp
Labels: Code cleanup

#9525 Reformat python code to be compliant with PEP8
  src/searchengine/nova/helpers.py
  src/searchengine/nova/nova2.py
  src/searchengine/nova/nova2dl.py
  src/searchengine/nova/novaprinter.py
  src/searchengine/nova3/helpers.py
  src/searchengine/nova3/nova2.py
  src/searchengine/nova3/nova2dl.py
  src/searchengine/nova3/novaprinter.py
Labels: Code cleanup

#9330 Revert "Print warning about cmake support status"
  CMakeLists.txt
Labels: Build system

#9575 Fix asking to install Python
  src/base/preferences.cpp
  src/base/preferences.h
  src/base/utils/foreignapps.cpp
  src/base/utils/foreignapps.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
Labels: Hotfix

#9611 Fix minor defects
  src/base/search/searchpluginmanager.cpp
  src/base/unicodestrings.h
  src/gui/categoryfilterwidget.h
  src/gui/transferlistmodel.h
Labels: Code cleanup
