Repository qbittorrent/qBittorrent, pull requests merged in 2018-08, with the labels that each got.

#9273 Set "close to tray" to false as default
  src/base/preferences.cpp
Labels: GUI

#9265 Never save resume data for already paused torrents
  src/base/bittorrent/session.cpp
Labels: Core

#9303 Fix I/O error after fetching magnet metadata
  src/base/bittorrent/session.cpp
Labels: Hotfix

#9244 Inhibit sleep for running downloads or uploads regardless of network activity
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/optionsdialog.ui
Labels: Core

#8538 Add a name filter for search results
  src/gui/mainwindow.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
  src/gui/search/searchwidget.cpp
  src/gui/search/searchwidget.h
Labels: GUI, Search engines

#9315 Fix lupdate errors
  src/base/net/downloadhandler.cpp
  src/base/net/downloadhandler.h
  src/lang/lang.pri
Labels: Hotfix

#9318 Fix regression that broke installing desktop file
  unixconf.pri
Labels: Hotfix

#9336 Fix mingw warning about unrecognized escape sequence
  src/qbittorrent_mingw.rc
Labels: Windows

#9346 Fix values sorted wrong in "Last Activity" column
  src/gui/transferlistsortmodel.cpp
Labels: GUI

#9357 Fix icon height/width ratio
  src/icons/.svgo.yml
  src/icons/skin/completed.svg
  src/icons/skin/error.svg
Labels: Look and Feel

#9365 Fix WebUI unreachable issue
  src/base/preferences.cpp
Labels: Hotfix, WebUI

#9314 Add option to use regexps in the search job's search filter's context menu
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/mainwindow.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
  src/gui/transferlistwidget.cpp
Labels: GUI

#9331 Allow setting seq & first/last from context menu without metadata
  src/gui/transferlistwidget.cpp
Labels: GUI

#9390 Save fastresumes when changing torrent priorities
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
Labels: Core
