Repository qbittorrent/qBittorrent, pull requests merged in 2018-10, with the labels that each got.

#9614 Fix minor JavaScript defects
  src/webui/www/private/preferences_content.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/download.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/lib/mocha.js
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/scripts/prop-general.js
  src/webui/www/private/scripts/prop-trackers.js
  src/webui/www/private/scripts/prop-webseeds.js
Labels: Code cleanup, WebUI

#9635 Use a more detailed alert mask where possible
  src/base/bittorrent/session.cpp
Labels: Performance

#8980 Clear LineEdit on ESC
  src/gui/lineedit/src/lineedit.cpp
  src/gui/lineedit/src/lineedit.h
Labels: GUI

#9600 Rewrite averaging code and reduce horizontal graphs resolution
  src/gui/properties/speedplotview.cpp
  src/gui/properties/speedplotview.h
Labels: GUI

#9691 cmake: restore out-of-source build
  cmake/Modules/QbtTranslations.cmake
  src/CMakeLists.txt
  src/app/CMakeLists.txt
  src/webui/webui.pri
  src/webui/www/translations/webui_translations.qrc
  src/webui/www/webui.qrc
Labels: Build system

#9710 Fix WebUI Auto TMM context menu bug
  src/webui/www/private/scripts/contextmenu.js
Labels: WebUI

#9698 Fix TravisCI cmake build on macOS
  .travis.yml
Labels: Build system

#9718 Bump WebAPI version
  src/webui/webapplication.h
Labels: WebAPI

#9766 Fix indentation in tstool.py
  src/webui/www/tstool.py
Labels: Hotfix

#9774 Consider empty locale setting as not set. Closes #9735
  src/base/preferences.cpp
Labels: Hotfix, WebUI

#9777 Fix Alternative Web UI to be available. Closes #9720
  src/webui/webapplication.cpp
Labels: Hotfix, WebUI
