Repository qbittorrent/qBittorrent, pull requests merged in 2019-04, with the labels that each got.

#10390 Add more libtorrent 1.2 builds to TravisCI
  .travis.yml
  configure
  configure.ac
Labels: Build system

#10449 Rename "Prefer encryption" to "Allow encryption"
  src/gui/optionsdialog.ui
  src/webui/www/private/preferences_content.html
Labels: GUI, WebUI

#10458 Correctly handle '+' sign in x-www-form-urlencoded data
  src/base/http/requestparser.cpp
Labels: WebAPI

#10438 Work around the crash occurred in QTimer
  src/webui/api/synccontroller.cpp
  src/webui/api/synccontroller.h
Labels: Crash

#10485 Always use index.html as default page
  src/webui/webapplication.cpp
  src/webui/www/public/index.html
  src/webui/www/webui.qrc
Labels: WebUI

#10473 Fix unsafe type narrowing (MSVC C4267 warning)
  src/base/utils/version.h
Labels: Code cleanup

#10492 Remove closed connections immediately
  src/base/http/server.cpp
  src/base/http/server.h
Labels: WebAPI

#10469 Reduce macOS CI build time
  .travis.yml
Labels: Build system

#10476 Set title attribute for all WebUI table cells
  src/webui/www/private/scripts/dynamicTable.js
Labels: WebUI

#10504 Misc improvements in WebUI
  src/webui/webapplication.cpp
  src/webui/webapplication.h
  src/webui/www/private/about.html
  src/webui/www/private/addtrackers.html
  src/webui/www/private/confirmdeletion.html
  src/webui/www/private/download.html
  src/webui/www/private/downloadlimit.html
  src/webui/www/private/edittracker.html
  src/webui/www/private/index.html
  src/webui/www/private/newcategory.html
  src/webui/www/private/preferences.html
  src/webui/www/private/rename.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/setlocation.html
  src/webui/www/private/shareratio.html
  src/webui/www/private/upload.html
  src/webui/www/private/uploadlimit.html
  src/webui/www/public/css/login.css
  src/webui/www/public/index.html
Labels: WebUI
