Repository qbittorrent/qBittorrent, pull requests merged in 2019-05, with the labels that each got.

#10537 Minor cleanups
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/settingvalue.h
  src/gui/torrentcategorydialog.cpp
  src/gui/torrentcontentmodel.cpp
  src/webui/webapplication.cpp
  src/webui/webapplication.h
Labels: Code cleanup, Performance

#10557 Fix "Create subfolder" option is not working in WebUI
  src/webui/www/private/download.html
  src/webui/www/private/scripts/download.js
  src/webui/www/private/upload.html
Labels: WebUI

#10565 Backport to v4_1_x
  src/webui/www/private/download.html
  src/webui/www/private/scripts/download.js
  src/webui/www/private/upload.html
Labels: WebUI

#10445 Work around crashing in Qt networking library
  src/gui/mainwindow.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
Labels: Crash

#10437 Migrate to update-to-date libtorrent functions
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/base/bittorrent/torrentinfo.cpp
  src/base/net/private/geoipdatabase.cpp
Labels: Code cleanup, Core

#10552 Register protocol handler in WebUI for magnet links
  src/webui/www/private/scripts/client.js
Labels: WebUI

#10607 Fix '+' char not decoded to space correctly
  src/base/bittorrent/tracker.cpp
  src/base/bittorrent/tracker.h
  src/base/http/requestparser.cpp
  src/base/http/types.h
  src/webui/webapplication.cpp
Labels: WebAPI

#10590 Don't turn screen blank when closed to system tray
  src/gui/mainwindow.cpp
Labels: GUI

#10618 Replace Bytes/s with KiB/s in the adding torrent dialogs in WebUI
  src/webui/www/private/download.html
  src/webui/www/private/upload.html
Labels: WebUI

#10633 Fix Travis-CI for macOS and libtorrent 1.1.x
  .travis.yml
Labels: OS: Mac OS X

#10591 Migrate to update-to-date libtorrent functions (part2)
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/infohash.cpp
  src/base/bittorrent/infohash.h
  src/base/bittorrent/magneturi.cpp
  src/base/bittorrent/magneturi.h
  src/base/bittorrent/peerinfo.cpp
  src/base/bittorrent/peerinfo.h
  src/base/bittorrent/private/filterparserthread.cpp
  src/base/bittorrent/private/filterparserthread.h
  src/base/bittorrent/private/libtorrentfwd.h
  src/base/bittorrent/private/portforwarderimpl.cpp
  src/base/bittorrent/private/portforwarderimpl.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrentcreatorthread.cpp
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/base/bittorrent/torrentinfo.cpp
  src/base/bittorrent/torrentinfo.h
  src/base/bittorrent/tracker.cpp
  src/base/bittorrent/tracker.h
  src/base/bittorrent/trackerentry.cpp
  src/base/bittorrent/trackerentry.h
Labels: Code cleanup, Core

#10600 Change "Add new torrent" dialog to horizontal layout
  src/base/unicodestrings.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.h
  src/gui/addnewtorrentdialog.ui
Labels: Look and Feel

#10638 Fix assertion fail
  src/base/bittorrent/torrentinfo.cpp
Labels: Core

#10627 Improve removeIf() to support other types
  src/base/algorithm.h
  src/base/bittorrent/session.cpp
  src/base/filesystemwatcher.cpp
  src/base/http/server.cpp
  src/base/preferences.cpp
  src/gui/properties/peerlistwidget.cpp
  src/webui/webapplication.cpp
Labels: Code cleanup

#10656 Code cleanups
  src/app/main.cpp
  src/base/algorithm.h
  src/base/bittorrent/magneturi.cpp
  src/base/bittorrent/magneturi.h
  src/base/bittorrent/peerinfo.h
  src/base/bittorrent/private/bandwidthscheduler.cpp
  src/base/bittorrent/private/filterparserthread.cpp
  src/base/bittorrent/private/filterparserthread.h
  src/base/bittorrent/private/portforwarderimpl.cpp
  src/base/bittorrent/private/resumedatasavingmanager.cpp
  src/base/bittorrent/private/resumedatasavingmanager.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/base/bittorrent/torrentinfo.h
  src/base/filesystemwatcher.h
  src/base/http/requestparser.cpp
  src/base/iconprovider.h
  src/base/net/smtp.cpp
  src/base/preferences.cpp
  src/base/preferences.h
  src/base/private/profile_p.cpp
  src/base/profile.h
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_autodownloadrule.h
  src/base/scanfoldersmodel.cpp
  src/base/search/searchhandler.h
  src/base/search/searchpluginmanager.cpp
  src/base/settingvalue.h
  src/base/utils/bytearray.cpp
  src/base/utils/bytearray.h
  src/base/utils/foreignapps.cpp
  src/base/utils/fs.cpp
  src/base/utils/misc.cpp
  src/base/utils/misc.h
  src/base/utils/password.cpp
  src/base/utils/random.cpp
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/propertieswidget.h
  src/gui/properties/speedwidget.cpp
  src/gui/properties/speedwidget.h
  src/gui/torrentcontenttreeview.cpp
  src/gui/transferlistdelegate.cpp
  src/webui/api/appcontroller.cpp
  src/webui/api/authcontroller.cpp
  src/webui/api/authcontroller.h
  src/webui/webapplication.cpp
  src/webui/www/private/preferences_content.html
Labels: Code cleanup

#10675 Replace QList by QVector for tracker related operations
  src/base/bittorrent/magneturi.cpp
  src/base/bittorrent/magneturi.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/base/bittorrent/torrentinfo.cpp
  src/base/bittorrent/torrentinfo.h
  src/base/bittorrent/trackerentry.h
  src/gui/properties/trackerlistwidget.cpp
  src/gui/properties/trackersadditiondialog.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
  src/webui/api/torrentscontroller.cpp
Labels: Code cleanup

#10684 Replace CheckBox with Arrow in transferlistfilterswidget
  src/gui/transferlistfilterswidget.cpp
Labels: Look and Feel

#10637 Use newer libtorrent API (part 3)
  src/base/bittorrent/trackerentry.cpp
  src/base/bittorrent/trackerentry.h
Labels: Core

#10705 Fix wrong logic
  src/base/bittorrent/trackerentry.cpp
Labels: Hotfix

#10690 Various visual tweaks
  src/gui/lineedit/src/lineedit.cpp
  src/gui/optionsdialog.ui
Labels: Look and Feel

#10723 Fix sequential downloading when redirected
  src/base/net/downloadmanager.cpp
Labels: Hotfix, Network

#10720 Fix arrow too large on macOS
  src/gui/transferlistfilterswidget.cpp
Labels: Hotfix, Look and Feel

#10721 Fix wrong comparison result
  src/base/utils/string.cpp
Labels: Core

#10728 Fix sequential downloading when redirected
  src/base/net/downloadmanager.cpp
Labels: Hotfix, Network
