Repository qbittorrent/qBittorrent, pull requests merged in 2019-03, with the labels that each got.

#10323 Replace deprecated functions/variables
  src/CMakeLists.txt
  src/base/bittorrent/session.cpp
  src/base/http/server.cpp
  src/base/utils/misc.cpp
  src/gui/advancedsettings.cpp
  src/gui/properties/speedwidget.cpp
  src/gui/properties/speedwidget.h
  src/gui/search/searchwidget.cpp
  src/gui/search/searchwidget.h
  src/src.pro
Labels: Code cleanup

#10302 Replace QScopedPointer with std::unqiue_ptr
  src/app/main.cpp
  src/base/profile.cpp
  src/base/profile.h
  src/base/rss/rss_feed.cpp
  src/gui/addnewtorrentdialog.h
  src/gui/fspathedit.cpp
  src/gui/fspathedit.h
Labels: Code cleanup

#10332 Update INSTALL file
  INSTALL
Labels: Documentation

#10345 Avoid crashes on torrent search
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchwidget.cpp
Labels: Hotfix

#10340 Move helper functions to Utils::Gui namespace
  src/app/application.cpp
  src/app/cmdoptions.cpp
  src/app/main.cpp
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/base/bittorrent/torrentinfo.cpp
  src/base/bittorrent/torrentinfo.h
  src/base/utils/misc.cpp
  src/base/utils/misc.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/macutilities.h
  src/gui/macutilities.mm
  src/gui/mainwindow.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
  src/gui/shutdownconfirmdialog.cpp
  src/gui/transferlistmodel.cpp
  src/gui/transferlistsortmodel.cpp
  src/gui/transferlistwidget.cpp
  src/gui/utils.cpp
  src/gui/utils.h
  src/webui/api/serialize/serialize_torrent.cpp
Labels: Code cleanup

#10346 Improve "Download manager"
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/net/dnsupdater.cpp
  src/base/net/dnsupdater.h
  src/base/net/downloadhandler.cpp
  src/base/net/downloadhandler.h
  src/base/net/downloadmanager.cpp
  src/base/net/downloadmanager.h
  src/base/net/geoipmanager.cpp
  src/base/net/geoipmanager.h
  src/base/rss/rss_feed.cpp
  src/base/rss/rss_feed.h
  src/base/search/searchpluginmanager.cpp
  src/base/search/searchpluginmanager.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/programupdater.cpp
  src/gui/programupdater.h
  src/gui/properties/trackersadditiondialog.cpp
  src/gui/properties/trackersadditiondialog.h
  src/gui/search/pluginselectdialog.cpp
  src/gui/search/pluginselectdialog.h
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
Labels: Core, Network

#10355 Improve AdvancedSettings::addRow()
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
Labels: GUI

#9702 Fix building qbittorrent-nox on Windows
  src/app/cmdoptions.cpp
  src/app/cmdoptions.h
  src/app/main.cpp
Labels: OS: Windows

#10365 Add documentation links to some advanced settings
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/gui/properties/trackerlistwidget.cpp
  src/webui/www/private/scripts/dynamicTable.js
Labels: GUI

#10366 Avoid performance penalty when logger is full
  src/app/application.cpp
  src/app/filelogger.cpp
  src/app/filelogger.h
  src/base/logger.cpp
  src/base/logger.h
  src/gui/executionlogwidget.cpp
  src/gui/executionlogwidget.ui
  src/gui/loglistwidget.cpp
  src/gui/loglistwidget.h
Labels: Code cleanup, Core

#10214 Remove autocorrect/autocapitalise in WebUI
  src/webui/www/private/download.html
  src/webui/www/private/preferences_content.html
  src/webui/www/private/setlocation.html
  src/webui/www/private/upload.html
Labels: WebUI

#10400 Make num enter key work the same as return in searchjobwidget
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
Labels: GUI

#10396 Document current WebUI browser compatibility
  src/webui/www/README.md
Labels: Project management
