Repository qbittorrent/qBittorrent, pull requests merged in 2019-07, with the labels that each got.

#10866 Incorporate QtSingleApplication logic into qBittorrent codebase
  configure
  configure.ac
  src/CMakeLists.txt
  src/app/CMakeLists.txt
  src/app/app.pri
  src/app/application.cpp
  src/app/application.h
  src/app/applicationinstancemanager.cpp
  src/app/applicationinstancemanager.h
  src/app/qtlocalpeer/qtlocalpeer.cpp
  src/app/qtlocalpeer/qtlocalpeer.h
  src/app/qtlocalpeer/qtlockedfile.cpp
  src/app/qtlocalpeer/qtlockedfile.h
  src/app/qtlocalpeer/qtlockedfile_unix.cpp
  src/app/qtlocalpeer/qtlockedfile_win.cpp
  src/app/qtsingleapplication/CMakeLists.txt
  src/app/qtsingleapplication/QtLockedFile
  src/app/qtsingleapplication/QtSingleApplication
  src/app/qtsingleapplication/qtlockedfile.h
  src/app/qtsingleapplication/qtsingleapplication.cpp
  src/app/qtsingleapplication/qtsingleapplication.pri
  src/app/qtsingleapplication/qtsinglecoreapplication.cpp
  src/app/qtsingleapplication/qtsinglecoreapplication.h
  src/app/qtsingleapplication/qtsinglecoreapplication.pri
  src/gui/CMakeLists.txt
Labels: Code cleanup, Core

#10874 Replace obsoleted Qt functions
  src/app/main.cpp
  src/base/search/searchdownloadhandler.cpp
  src/base/search/searchhandler.cpp
  src/gui/autoexpandabledialog.cpp
  src/gui/properties/speedplotview.cpp
Labels: Code cleanup

#10879 Add more libtorrent options to Advanced Settings
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
Labels: Core

#10870 Use newer libtorrent API (part 5)
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrenthandle.cpp
Labels: Core

#10871 Fix torrent checking issues
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
Labels: Core

#10702 Allow Styling through QSS
  src/app/application.cpp
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/CMakeLists.txt
  src/gui/gui.pri
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/optionsdialog.ui
  src/gui/uithememanager.cpp
  src/gui/uithememanager.h
Labels: Look and Feel

#10867 Avoid word wrap in webui footer
  src/webui/www/private/css/Layout.css
Labels: WebUI

#10916 Implement tri-state checkbox action in menu
  src/gui/CMakeLists.txt
  src/gui/gui.pri
  src/gui/private/tristatewidget.cpp
  src/gui/private/tristatewidget.h
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
  src/gui/tristateaction.cpp
  src/gui/tristateaction.h
Labels: GUI

#9995 Rename priority to queue in the context of torrents
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/mainwindow.ui
  src/gui/transferlistdelegate.cpp
  src/gui/transferlistmodel.cpp
  src/gui/transferlistmodel.h
  src/gui/transferlistsortmodel.cpp
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
  src/webui/api/serialize/serialize_torrent.cpp
  src/webui/api/serialize/serialize_torrent.h
  src/webui/api/synccontroller.cpp
  src/webui/api/torrentscontroller.cpp
  src/webui/www/private/filters.html
  src/webui/www/private/index.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/transferlist.html
Labels: GUI, WebUI

#10910 Avoid race conditions when adding torrent
  src/base/bittorrent/session.cpp
Labels: Core

#10918 Various code clean up
  src/app/CMakeLists.txt
  src/gui/CMakeLists.txt
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/gui/cookiesdialog.h
  src/gui/executionlogwidget.h
  src/gui/gui.pri
  src/gui/lineedit.cpp
  src/gui/lineedit.h
  src/gui/lineedit/CMakeLists.txt
  src/gui/lineedit/lineedit.pri
  src/gui/powermanagement/CMakeLists.txt
  src/gui/properties/CMakeLists.txt
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/peerlistwidget.h
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/propertieswidget.h
  src/gui/properties/proplistdelegate.cpp
  src/gui/properties/speedwidget.cpp
  src/gui/properties/speedwidget.h
  src/gui/properties/trackerlistwidget.cpp
  src/gui/properties/trackerlistwidget.h
  src/gui/qtnotify/CMakeLists.txt
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/rss/automatedrssdownloader.h
  src/gui/rss/rsswidget.cpp
  src/gui/rss/rsswidget.h
  src/gui/search/CMakeLists.txt
  src/gui/search/searchjobwidget.h
  src/gui/search/searchwidget.cpp
  src/gui/search/searchwidget.h
  src/gui/torrentcontentmodelfolder.cpp
  src/gui/torrentcontentmodelitem.cpp
  src/gui/torrentcreatordialog.h
  src/gui/transferlistdelegate.h
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
  src/webui/CMakeLists.txt
Labels: Code cleanup

#10877 Add advanced options in WebUI
  src/webui/api/appcontroller.cpp
  src/webui/api/appcontroller.h
  src/webui/www/private/preferences.html
  src/webui/www/private/preferences_content.html
Labels: WebUI

#10921 Ignore some actions on uninitialized torrents
  src/base/bittorrent/torrenthandle.cpp
Labels: Core

#10926 Move registering WebUI magnet handler behind toolbar option
  src/webui/www/private/index.html
  src/webui/www/private/scripts/client.js
Labels: WebUI

#10914 Incorporate GuiIconProvider inside UIThemeManager
  src/app/application.cpp
  src/gui/CMakeLists.txt
  src/gui/addnewtorrentdialog.cpp
  src/gui/categoryfiltermodel.cpp
  src/gui/categoryfilterwidget.cpp
  src/gui/cookiesdialog.cpp
  src/gui/deletionconfirmationdialog.h
  src/gui/executionlogwidget.cpp
  src/gui/gui.pri
  src/gui/guiiconprovider.cpp
  src/gui/guiiconprovider.h
  src/gui/lineedit.cpp
  src/gui/loglistwidget.cpp
  src/gui/mainwindow.cpp
  src/gui/optionsdialog.cpp
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/proptabbar.cpp
  src/gui/properties/trackerlistwidget.cpp
  src/gui/properties/trackersadditiondialog.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/rss/feedlistwidget.cpp
  src/gui/rss/rsswidget.cpp
  src/gui/search/pluginselectdialog.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchwidget.cpp
  src/gui/tagfiltermodel.cpp
  src/gui/tagfilterwidget.cpp
  src/gui/torrentcontentmodel.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistwidget.cpp
  src/gui/uithememanager.cpp
  src/gui/uithememanager.h
Labels: GUI

#10934 Rely on Qt ownership to delete class members
  src/base/net/geoipmanager.cpp
  src/base/net/reverseresolution.cpp
  src/base/profile.cpp
  src/base/profile.h
  src/gui/previewselectdialog.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/proptabbar.cpp
  src/gui/properties/proptabbar.h
  src/gui/rss/feedlistwidget.cpp
  src/gui/rss/feedlistwidget.h
  src/gui/torrentcontentfiltermodel.cpp
  src/gui/torrentcontentfiltermodel.h
  src/gui/transferlistwidget.cpp
  src/webui/webapplication.cpp
Labels: Code cleanup

#10929 Fix torrent checking issues (backport to v4.1.x)
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
Labels: Core

#10931 Add WebUI support for triggering context menus on mobile
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/dynamicTable.js
Labels: WebUI

#10944 Improve CMake build system
  .travis.yml
  cmake/Modules/MacroQbtCompilerSettings.cmake
  src/CMakeLists.txt
Labels: Build system

#10946 Add override keyword to functions
  .travis.yml
  cmake/Modules/MacroQbtCompilerSettings.cmake
  src/app/qtlocalpeer/qtlockedfile.h
  src/base/bittorrent/private/filterparserthread.h
  src/base/bittorrent/torrentcreatorthread.h
  src/base/bittorrent/tracker.h
  src/base/http/server.h
  src/base/scanfoldersmodel.h
  src/gui/rss/feedlistwidget.h
  src/gui/rss/htmlbrowser.h
Labels: Code cleanup

#10949 Prevent command injection via "Run external program" function
  src/app/application.cpp
Labels: Core

#10953 Backport to v4_1_x
  src/app/application.cpp
Labels: Core

#10951 Improve CMake configuration
  .gitignore
  cmake/Modules/FindLibtorrentRasterbar.cmake
  cmake/Modules/FindQtSingleApplication.cmake
  cmake/Modules/winconf-mingw.cmake
  cmake/Modules/winconf-msvc.cmake
  cmake/Modules/winconf.cmake
Labels: Build system

#10950 Don't use deprecated libtorrent features
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/private/ltunderlyingtype.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrentcreatorthread.cpp
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrentinfo.cpp
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/optionsdialog.ui
  src/webui/api/appcontroller.cpp
  src/webui/www/private/preferences_content.html
Labels: Core

#10839 Update remaining size of ignored files to 0
  src/gui/torrentcontentmodelitem.cpp
Labels: GUI

#10961 Save updated resume data for completed torrents
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
Labels: Core

#10527 Implement tag management for WebUI
  src/webui/api/synccontroller.cpp
  src/webui/api/torrentscontroller.cpp
  src/webui/api/torrentscontroller.h
  src/webui/www/private/addtrackers.html
  src/webui/www/private/confirmdeletion.html
  src/webui/www/private/css/style.css
  src/webui/www/private/download.html
  src/webui/www/private/downloadlimit.html
  src/webui/www/private/edittracker.html
  src/webui/www/private/filters.html
  src/webui/www/private/index.html
  src/webui/www/private/installsearchplugin.html
  src/webui/www/private/newcategory.html
  src/webui/www/private/newtag.html
  src/webui/www/private/preferences_content.html
  src/webui/www/private/properties_content.html
  src/webui/www/private/rename.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/download.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/scripts/progressbar.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/scripts/prop-general.js
  src/webui/www/private/scripts/prop-peers.js
  src/webui/www/private/scripts/prop-trackers.js
  src/webui/www/private/scripts/prop-webseeds.js
  src/webui/www/private/scripts/speedslider.js
  src/webui/www/private/search.html
  src/webui/www/private/searchplugins.html
  src/webui/www/private/setlocation.html
  src/webui/www/private/shareratio.html
  src/webui/www/private/transferlist.html
  src/webui/www/private/upload.html
  src/webui/www/private/uploadlimit.html
  src/webui/www/public/scripts/login.js
  src/webui/www/webui.qrc
Labels: WebAPI, WebUI

#10967 Save updated resume data for completed torrents (backport to v4.1.x)
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
Labels: Core

#10973 Improve parsing in BitTorrent::PeerAddress::parse
  src/base/bittorrent/peeraddress.cpp
  src/base/bittorrent/peeraddress.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
Labels: Code cleanup

#10954 Add availability column
  src/gui/transferlistdelegate.cpp
  src/gui/transferlistmodel.cpp
  src/gui/transferlistmodel.h
  src/webui/api/serialize/serialize_torrent.cpp
  src/webui/api/serialize/serialize_torrent.h
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/misc.js
Labels: GUI, WebUI

#10941 Fix WebUI removing parameters from magnet links
  src/webui/www/private/download.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/mocha-init.js
Labels: WebUI

#10988 Fix incomplete file extension not applied for new torrents
  src/base/bittorrent/torrenthandle.cpp
Labels: Hotfix

#10970 Add context menu to Web UI search table
  src/webui/www/private/scripts/client.js
  src/webui/www/private/search.html
Labels: WebUI

#10982 Code base cleanup
  src/app/qtlocalpeer/qtlocalpeer.cpp
  src/app/qtlocalpeer/qtlocalpeer.h
  src/app/qtlocalpeer/qtlockedfile.cpp
  src/app/qtlocalpeer/qtlockedfile.h
  src/app/qtlocalpeer/qtlockedfile_unix.cpp
  src/app/qtlocalpeer/qtlockedfile_win.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrenthandle.cpp
  src/base/net/smtp.cpp
  src/base/private/profile_p.cpp
  src/base/rss/private/rss_parser.cpp
  src/gui/CMakeLists.txt
  src/gui/addnewtorrentdialog.cpp
  src/gui/advancedsettings.cpp
  src/gui/fspathedit.cpp
  src/gui/gui.pri
  src/gui/mainwindow.cpp
  src/gui/optionsdialog.cpp
  src/gui/private/fspathedit_p.cpp
  src/gui/private/fspathedit_p.h
  src/gui/programupdater.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/proptabbar.cpp
  src/gui/properties/speedwidget.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/scanfoldersdelegate.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchwidget.cpp
  src/gui/speedlimitdialog.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/updownratiodialog.cpp
Labels: Code cleanup

#10993 Adjust wording to sound more natural
  src/gui/properties/peerlistwidget.cpp
Labels: GUI
