Repository qbittorrent/qBittorrent, pull requests merged in 2019-09, with the labels that each got.

#11157 Construct QHostAddress more efficiently
  src/base/bittorrent/peerinfo.cpp
Labels: Code cleanup

#11104 Fix unable to remove web seeds
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrenthandle.cpp
Labels: Core

#11171 Conditionally disable port input field
  src/webui/www/private/views/preferences.html
Labels: WebUI

#11179 Fix ambiguity in GitHub Issue template
  .github/ISSUE_TEMPLATE.md
Labels: Project management

#11183 Always save info dict when saving fastresume (backport to v4_1_x)
  src/base/bittorrent/torrenthandle.cpp
Labels: Backport

#11181 Add check for null pointer
  src/base/bittorrent/session.cpp
Labels: Hotfix

#11182 Move error logging of adding peers to the proper place
  src/base/bittorrent/peeraddress.cpp
  src/base/bittorrent/peeraddress.h
  src/base/bittorrent/torrenthandle.cpp
  src/gui/properties/peerlistwidget.cpp
Labels: Core

#11154 Remove max character limit of location path
  src/webui/www/private/setlocation.html
Labels: WebUI

#11201 Treat .magnet file extension as case insensitive in filesystem watcher
  src/base/filesystemwatcher.cpp
  src/base/scanfoldersmodel.cpp
Labels: Core

#11195 Replace deprecated macro
  CODING_GUIDELINES.md
  src/CMakeLists.txt
  src/app/application.cpp
  src/app/application.h
  src/app/main.cpp
  src/base/filesystemwatcher.cpp
  src/base/preferences.cpp
  src/base/preferences.h
  src/base/private/profile_p.cpp
  src/base/utils/fs.cpp
  src/base/utils/misc.cpp
  src/base/utils/string.cpp
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/gui/categoryfilterwidget.cpp
  src/gui/executionlogwidget.cpp
  src/gui/hidabletabwidget.cpp
  src/gui/hidabletabwidget.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/powermanagement/powermanagement.cpp
  src/gui/powermanagement/powermanagement.h
  src/gui/programupdater.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/proptabbar.cpp
  src/gui/rss/rsswidget.cpp
  src/gui/search/searchwidget.cpp
  src/gui/statusbar.cpp
  src/gui/tagfilterwidget.cpp
  src/gui/torrentcontentmodel.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistwidget.cpp
  src/gui/uithememanager.cpp
  src/gui/uithememanager.h
  src/gui/utils.cpp
Labels: Code cleanup

#11208 Improve SettingsStorage behavior
  src/base/settingsstorage.cpp
  src/base/settingvalue.h
Labels: Core

#11212 Add option to align file to piece boundary when creating new torrent
  src/base/bittorrent/torrentcreatorthread.cpp
  src/base/bittorrent/torrentcreatorthread.h
  src/gui/torrentcreatordialog.cpp
  src/gui/torrentcreatordialog.h
  src/gui/torrentcreatordialog.ui
Labels: GUI

#11227 Handle "alerts dropped" alert from libtorrent
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
Labels: Core

#11232 Revise HTML escaping in GUI
  src/base/bittorrent/session.cpp
  src/gui/addnewtorrentdialog.cpp
  src/gui/properties/propertieswidget.cpp
Labels: GUI, Security

#11103 Move JavaScript code into explicit namespaces
  src/webui/www/private/addpeers.html
  src/webui/www/private/download.html
  src/webui/www/private/newcategory.html
  src/webui/www/private/newtag.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/download.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/file-tree.js
  src/webui/www/private/scripts/filesystem.js
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/scripts/preferences.js
  src/webui/www/private/scripts/progressbar.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/scripts/prop-general.js
  src/webui/www/private/scripts/prop-peers.js
  src/webui/www/private/scripts/prop-trackers.js
  src/webui/www/private/scripts/prop-webseeds.js
  src/webui/www/private/setlocation.html
  src/webui/www/private/shareratio.html
  src/webui/www/private/upload.html
  src/webui/www/private/views/about.html
  src/webui/www/private/views/aboutToolbar.html
  src/webui/www/private/views/filters.html
  src/webui/www/private/views/installsearchplugin.html
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/preferencesToolbar.html
  src/webui/www/private/views/properties.html
  src/webui/www/private/views/search.html
  src/webui/www/private/views/searchplugins.html
  src/webui/www/private/views/transferlist.html
Labels: WebUI

#11235 Allow to retry fetching RSS feeds. Closes #11168
  src/base/net/downloadmanager.cpp
  src/base/net/downloadmanager.h
  src/base/rss/rss_feed.cpp
  src/base/rss/rss_feed.h
Labels: RSS

#11240 Revise HTML escaping in GUI (Backport)
  src/gui/addnewtorrentdialog.cpp
  src/gui/properties/propertieswidget.cpp
Labels: Backport

#11250 Improve error messages for url_seed_alert
  src/base/bittorrent/session.cpp
Labels: Core

#11254 Fix seeding failed after creating a new torrent
  src/gui/torrentcreatordialog.cpp
Labels: GUI

#11215 WebUI: fix escaping of HTML special characters
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/scripts/prop-general.js
  src/webui/www/private/scripts/prop-peers.js
  src/webui/www/private/scripts/prop-trackers.js
Labels: Security, WebUI

#11264 Add ability to trigger actions via keypad enter key
  src/gui/properties/propertieswidget.cpp
  src/gui/transferlistwidget.cpp
Labels: GUI

#11251 Move "torrent status report" functionality out of Session class
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/transferlistfilterswidget.cpp
Labels: Code cleanup

#11259 Revise TriStateBool class
  src/base/rss/rss_autodownloadrule.cpp
  src/base/tristatebool.h
Labels: Code cleanup

#11269 Improve "stats updated" signal handling in MainWindow class
  src/base/bittorrent/session.cpp
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
Labels: GUI

#11270 Use non-recursive mutex
  src/base/logger.cpp
  src/base/settingsstorage.cpp
Labels: Code cleanup

#11241 Add "Remove torrent and its files" option to share ratio limiting
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.ui
  src/gui/transferlistwidget.cpp
  src/webui/api/torrentscontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: Core, GUI
