Repository qbittorrent/qBittorrent, pull requests merged in 2019-06, with the labels that each got.

#10732 Avoid using deprecated stats_alert
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/mainwindow.cpp
  src/gui/rss/rsswidget.cpp
Labels: Code cleanup, Core

#10734 Use native folder icon in content tree
  src/gui/torrentcontentmodel.cpp
Labels: Look and Feel

#10737 Use timestamp from alert
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
Labels: Core

#10742 Ignore RSS articles with non-unique identifiers
  src/base/rss/private/rss_parser.cpp
  src/base/rss/private/rss_parser.h
  src/base/rss/rss_feed.cpp
Labels: RSS

#10741 Fix speed limit not applying to IPv6 peers
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
Labels: Core

#10754 Disable "Upload mode" when start preloaded torrent. Closes #10751
  src/base/bittorrent/session.cpp
Labels: Core

#10763 Use Qt5 connect syntax
  src/gui/previewselectdialog.cpp
  src/gui/transferlistwidget.cpp
Labels: Code cleanup

#10750 Fix unable to control add torrent dialogs when opened simultaneously
  src/gui/addnewtorrentdialog.cpp
  src/gui/downloadfromurldialog.cpp
  src/gui/search/searchjobwidget.cpp
Labels: Code cleanup, GUI

#10775 Misc. improvements
  .travis.yml
  src/base/utils/misc.cpp
Labels: Build system, Code cleanup

#10781 Avoid double lookup
  src/webui/api/appcontroller.cpp
Labels: WebAPI

#10769 Fix unable to rename folder on Windows. Closes #9151.
  src/base/bittorrent/torrenthandle.cpp
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.h
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/propertieswidget.h
  src/gui/torrentcontenttreeview.cpp
  src/gui/torrentcontenttreeview.h
Labels: GUI

#10800 Focus behavior row in Options dialog
  src/gui/optionsdialog.ui
Labels: Look and Feel

#10792 Remove empty leftover folders after rename properly
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/base/utils/string.cpp
  src/base/utils/string.h
  src/gui/torrentcontenttreeview.cpp
Labels: Core

#10801 Add WebAPI session timeout settings
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.ui
  src/webui/api/appcontroller.cpp
  src/webui/webapplication.cpp
  src/webui/webapplication.h
  src/webui/www/private/preferences_content.html
Labels: WebAPI

#10811 Rename "fromNativePath" to "toUniformPath"
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrentinfo.cpp
  src/base/preferences.cpp
  src/base/rss/rss_autodownloadrule.cpp
  src/base/rss/rss_feed.cpp
  src/base/scanfoldersmodel.cpp
  src/base/search/searchpluginmanager.cpp
  src/base/utils/fs.cpp
  src/base/utils/fs.h
  src/gui/fspathedit.cpp
  src/gui/mainwindow.cpp
  src/gui/search/pluginselectdialog.cpp
  src/gui/torrentcontentmodel.cpp
  src/gui/torrentcreatordialog.cpp
  src/gui/utils.cpp
  src/webui/api/appcontroller.cpp
Labels: Code cleanup

#10710 Add some padding to macOS app icon
  dist/mac/qbittorrent_mac.icns
Labels: Look and Feel

#10786 Avoid creating unnecessary event loops
  src/gui/addnewtorrentdialog.cpp
  src/gui/categoryfilterwidget.cpp
  src/gui/categoryfilterwidget.h
  src/gui/fspathedit_p.cpp
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/optionsdialog.cpp
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/propertieswidget.h
  src/gui/properties/speedwidget.cpp
  src/gui/properties/trackerlistwidget.cpp
  src/gui/properties/trackerlistwidget.h
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/rss/rsswidget.cpp
  src/gui/search/pluginselectdialog.cpp
  src/gui/search/pluginselectdialog.h
  src/gui/search/searchjobwidget.cpp
  src/gui/tagfilterwidget.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
  src/gui/transferlistwidget.cpp
Labels: GUI

#10830 Fix CMake Windows compilation
  cmake/Modules/winconf-mingw.cmake
  cmake/Modules/winconf.cmake
  src/base/utils/misc.h
Labels: Build system

#10838 Fix WebUI encoding of special characters
  src/webui/www/private/rename.html
Labels: WebUI

#10835 Avoid creating unnecessary event loops
  src/gui/optionsdialog.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
  src/gui/torrentcategorydialog.cpp
  src/gui/transferlistwidget.cpp
Labels: GUI

#10833 Use functor based QMetaObject::invokeMethod
  cmake/Modules/FindLibtorrentRasterbar.cmake
  conf.pri.windows
  src/base/asyncfilestorage.cpp
  src/base/bittorrent/session.cpp
  src/base/rss/private/rss_parser.cpp
  winconf.pri
Labels: Code cleanup

#10842 Backport to v4_1_x
  src/webui/www/private/rename.html
  src/webui/www/private/scripts/mocha-init.js
Labels: WebUI

#10843 Remove workaround for boost 1.39
  CMakeLists.txt
  INSTALL
  cmake/Modules/winconf.cmake
  configure
  configure.ac
  winconf.pri
Labels: Build system

#10844 Remove upper limit of disk cache setting
  src/base/bittorrent/session.cpp
  src/base/utils/random.cpp
  src/base/utils/random.h
  src/gui/advancedsettings.cpp
  src/webui/api/searchcontroller.cpp
Labels: Code cleanup, Core

#10850 Right click menu improvements
  src/gui/addnewtorrentdialog.cpp
  src/gui/mainwindow.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
Labels: GUI

#10853 Adjust open file descriptor limit on startup
  src/app/main.cpp
Labels: Core

#10852 Improvements to search widget
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
  src/gui/search/searchwidget.cpp
  src/gui/search/searchwidget.h
  src/gui/search/searchwidget.ui
Labels: GUI

#10864 Tighten up qtsingleapplication
  src/app/qtsingleapplication/qtlocalpeer.cpp
Labels: Core

#10865 Use newer libtorrent API (part 4)
  src/base/bittorrent/torrenthandle.cpp
Labels: Core
