Repository qbittorrent/qBittorrent, pull requests merged in 2019-11, with the labels that each got.

#11426 Add option to control qBittorrent process memory priority
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
Labels: OS: Windows

#11430 Fix integer narrowing on x86
  src/app/application.cpp
  src/base/bittorrent/session.cpp
  src/base/search/searchpluginmanager.cpp
  src/base/utils/fs.cpp
  src/gui/downloadfromurldialog.cpp
  src/gui/transferlistmodel.cpp
  src/webui/api/serialize/serialize_torrent.cpp
Labels: Code cleanup, Core

#11437 Fix integer narrowing on x86 (backport)
  src/base/utils/fs.cpp
Labels: Backport

#11422 Reserve memory for file data buffers
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrenthandle.cpp
Labels: Core

#11374 Fix country name misspelling
  src/base/net/geoipmanager.cpp
Labels: GUI

#11356 Allow to select multiple entries in "banned IP" dialog
  src/gui/banlistoptionsdialog.cpp
  src/gui/banlistoptionsdialog.ui
Labels: GUI

#11317 Fix "preview file" action not working
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/gui/previewselectdialog.cpp
  src/gui/previewselectdialog.h
  src/gui/previewselectdialog.ui
  src/gui/transferlistwidget.cpp
Labels: GUI

#11446 Clean up in Session class
  src/base/bittorrent/session.cpp
Labels: Code cleanup

#11423 Order qbittorrent-nox@.service after network-online.target
  dist/unix/systemd/qbittorrent-nox@.service.in
Labels: OS: Linux

#11354 Reallow to pause checking torrents
  src/base/bittorrent/torrenthandle.cpp
Labels: Core

#11462 Fix CMake Windows compilation
  cmake/Modules/winconf-mingw.cmake
  cmake/Modules/winconf-msvc.cmake
Labels: Build system

#11466 Add "create subfolder" option to RSS auto-download rules
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_autodownloadrule.cpp
  src/base/rss/rss_autodownloadrule.h
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/rss/automatedrssdownloader.ui
Labels: RSS

#11489 Code cleanup
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/base/rss/rss_autodownloadrule.cpp
  src/base/rss/rss_autodownloadrule.h
  src/gui/transferlistwidget.cpp
  src/webui/api/apicontroller.cpp
  src/webui/api/apicontroller.h
  src/webui/api/appcontroller.cpp
  src/webui/api/rsscontroller.cpp
  src/webui/api/searchcontroller.cpp
  src/webui/api/torrentscontroller.cpp
  src/webui/api/transfercontroller.cpp
  src/webui/webapplication.cpp
Labels: Code cleanup

#11494 Reallow to force recheck torrents that aren't fully started
  src/base/bittorrent/torrenthandle.cpp
Labels: Core

#11493 Revise "speed limits" related code
  src/base/bittorrent/session.cpp
Labels: Core

#11472 Backport
  src/base/bittorrent/torrenthandle.cpp
Labels: Backport

#11499 Avoid session reconfiguration when limit has not changed
  src/base/bittorrent/session.cpp
Labels: Hotfix

#11505 Fix compilation for Windows 7 with MinGW
  src/base/bittorrent/session.cpp
Labels: Core

#11474 Bump Web API version
  src/webui/webapplication.h
Labels: WebAPI

#11535 Migrate away from deprecated API
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrentinfo.cpp
Labels: Code cleanup
