Repository qbittorrent/qBittorrent, pull requests merged in 2020-10, with the labels that each got.

#13468 Correctly fill whole width of graph
  src/gui/properties/speedplotview.cpp
Labels: GUI

#13463 Fix CMake generated qBittorrent's version string
  cmake/Modules/MacroQbtCommonConfig.cmake
Labels: Build system

#13480 Fix packages installation on Ubuntu CI
  .github/workflows/ci.yaml
Labels: CI

#13439 Clazy fixes
  src/app/cmdoptions.cpp
  src/base/bittorrent/tracker.cpp
Labels: Code cleanup, Core

#12086 Clean ups
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/rss/rss_session.cpp
  src/base/rss/rss_session.h
  src/gui/rss/rsswidget.cpp
  src/gui/rss/rsswidget.h
  src/webui/api/appcontroller.cpp
Labels: Code cleanup

#13484 Fix image not loading under proxy
  src/gui/advancedsettings.cpp
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/views/preferences.html
Labels: GUI, WebUI

#13487 Add support for creating v2 torrents
  src/base/bittorrent/torrentcreatorthread.cpp
  src/base/bittorrent/torrentcreatorthread.h
  src/gui/torrentcreatordialog.cpp
  src/gui/torrentcreatordialog.h
  src/gui/torrentcreatordialog.ui
Labels: GUI

#13495 Fix regression of not hiding zero values in the peer list
  src/gui/properties/peerlistwidget.cpp
  src/gui/transferlistmodel.cpp
Labels: GUI

#13499 Add option for hashing_threads setting
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: Core

#11644 Don't create 'data' subdirectory on Linux
  CONTRIBUTING.md
  src/base/profile_p.cpp
Labels: Core, OS: Linux

#13395 Implement disk IO thread wrapper
  src/base/bittorrent/customstorage.cpp
  src/base/bittorrent/customstorage.h
  src/base/bittorrent/session.cpp
Labels: Core

#13465 Enable the use of middle-click to close tabs
  src/gui/search/searchwidget.cpp
  src/gui/search/searchwidget.h
Labels: GUI

#13414 Disallow CMake build failures on Travis
  .travis.yml
Labels: CI

#13537 Place WebUI RSS description in sandboxed iframe
  src/webui/www/private/views/rss.html
Labels: RSS, Security, WebUI

#13534 CMake: Bump version number
  CMakeLists.txt
Labels: Build system

#13563 Fix typo in connection.cpp
  src/base/http/connection.cpp
Labels: Code cleanup

#13540 NSIS: Update Italian translation
  dist/windows/installer-translations/italian.nsi
Labels: NSIS, Translation

#13567 Fix typos
  Changelog
  src/app/qtlocalpeer/qtlockedfile.cpp
  src/base/bittorrent/magneturi.cpp
  src/gui/mainwindow.cpp
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/views/rss.html
Labels: Code cleanup

#13587 Avoid settings being reset via WebAPI
  src/webui/api/appcontroller.cpp
Labels: WebAPI

#13600 Fix toggling advanced option in WebUI
  src/webui/www/private/views/preferences.html
Labels: WebUI

#13614 Prevent resume data to be saved for removed torrent
  src/base/bittorrent/session.cpp
Labels: Core

#13620 Move qHash helper for libtorrent types to its own file
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/customstorage.cpp
  src/base/bittorrent/customstorage.h
  src/base/bittorrent/ltqhash.h
  src/base/bittorrent/torrenthandleimpl.cpp
Labels: Core

#13625 Expose contentPath in WebAPI torrents/info
  src/webui/api/serialize/serialize_torrent.cpp
  src/webui/api/serialize/serialize_torrent.h
  src/webui/webapplication.h
Labels: WebAPI

#13569 Fix the issue that IPv6 address can't be banned
  src/webui/api/synccontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: WebAPI, WebUI

#13639 Update GitHub Actions CI actions versions
  .github/workflows/ci.yaml
Labels: CI

#13636 Clarify protocol choice label
  src/gui/optionsdialog.ui
  src/webui/www/private/views/preferences.html
Labels: GUI

#13646 Fix crash when clicked outside the table of torrent content view
  src/gui/properties/propertieswidget.cpp
Labels: GUI

#13637 Improve compatibility with libtorrent 2.0
  src/base/bittorrent/peerinfo.cpp
  src/base/bittorrent/torrentinfo.cpp
  src/base/bittorrent/trackerentry.cpp
Labels: Core

#13658 Don't resume "paused" torrents when put into "checking" state by libtorrent
  src/base/bittorrent/nativetorrentextension.cpp
  src/base/bittorrent/nativetorrentextension.h
  src/base/bittorrent/torrenthandleimpl.cpp
Labels: Core

#13667 Remove outdated information
  src/webui/www/README.md
Labels: WebUI

#13668 Improve consistency between transfer list and torrent content view
  src/gui/torrentcontentmodel.cpp
  src/gui/transferlistmodel.cpp
Labels: GUI

#13683 Fix mingw64 build error
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
Labels: OS: Windows
