Repository qbittorrent/qBittorrent, pull requests merged in 2020-01, with the labels that each got.

#11798 Save resume data after recheck. Closes #11774
  src/base/bittorrent/torrenthandle.cpp
Labels: Core, Hotfix

#11829 Allow double-click in preview dialog
  src/gui/previewselectdialog.cpp
Labels: GUI

#11733 Tracker is errored only if all local endpoints fail
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/trackerentry.cpp
Labels: Core

#11838 Minor WebUI code cleanups
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/search.html
Labels: Code cleanup, WebUI

#11848 Change stop tracker timeout settings placement
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: Hotfix

#11862 Bump copyright year and other fixes
  dist/mac/Info.plist
  dist/windows/options.nsi
  src/gui/aboutdialog.cpp
  src/gui/mainwindow.cpp
  src/qbittorrent.rc
  src/webui/www/private/views/about.html
Labels: Code cleanup

#11864 Fix Transfer list sorting
  src/gui/transferlistwidget.cpp
Labels: GUI, Hotfix

#11865 WebUI: Fix first row renaming in files tab
  src/webui/www/private/scripts/prop-files.js
Labels: WebUI

#11781 Add piece_extent_affinity to AdvancedSettings
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: Core

#11871 WebUI: Use correct operators in logical expressions
  src/webui/www/private/scripts/dynamicTable.js
Labels: WebUI

#11886 Migrate away from deprecated settings
  src/base/bittorrent/session.cpp
Labels: Code cleanup

#11088 Reorganize UI theme selection
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/optionsdialog.ui
Labels: GUI

#11892 CMake: Further CMake improvements and fixes
  cmake/Modules/MacroConfigureMSVCRuntime.cmake
  cmake/Modules/MacroGlibcDetect.cmake
  cmake/Modules/MacroQbtCompilerSettings.cmake
  src/CMakeLists.txt
  src/app/CMakeLists.txt
Labels: Build system

#11881 Simplify torrent startup handling
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/private/nativesessionextension.cpp
  src/base/bittorrent/private/nativesessionextension.h
  src/base/bittorrent/private/nativetorrentextension.cpp
  src/base/bittorrent/private/nativetorrentextension.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
Labels: Core

#11903 Show "∞" instead of " -1" in Preferences
  src/gui/optionsdialog.ui
Labels: GUI

#11914 Fix hide zero values
  src/gui/transferlistmodel.cpp
  src/gui/transferlistmodel.h
Labels: GUI, Hotfix

#11933 Improve qHash functions
  src/base/bittorrent/infohash.cpp
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/trackerentry.cpp
  src/base/net/downloadmanager.cpp
Labels: Core

#11950 Improve ReverseResolution class
  src/base/net/reverseresolution.cpp
  src/base/net/reverseresolution.h
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/peerlistwidget.h
Labels: Code cleanup
