Repository qbittorrent/qBittorrent, pull requests merged in 2020-03, with the labels that each got.

#12095 Let libtorrent decide whether to resume a torrent
  src/base/bittorrent/torrenthandle.cpp
Labels: Core

#12027 Improve the options tooltips
  src/gui/optionsdialog.ui
Labels: GUI

#12037 Check if file exists in seed mode
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
Labels: Core

#12108 Avoid unnecessary memory writes
  src/base/bittorrent/peerinfo.cpp
  src/base/bittorrent/torrenthandle.cpp
Labels: Code cleanup

#12121 Use proper type for piece index
  src/base/bittorrent/peerinfo.cpp
Labels: Hotfix

#12113 Use helper functions to construct smart pointers
  src/app/main.cpp
  src/base/bittorrent/private/nativesessionextension.cpp
  src/base/search/searchpluginmanager.cpp
  src/base/utils/fs.cpp
  src/base/utils/misc.cpp
  src/base/utils/misc.h
  src/gui/addnewtorrentdialog.cpp
Labels: Code cleanup

#12102 Delegate GUI scaling work to Qt
  src/app/main.cpp
  src/gui/utils.cpp
Labels: Discussion, GUI

#11813 Drop python2 support
  src/base/search/searchpluginmanager.cpp
  src/base/utils/foreignapps.cpp
  src/gui/mainwindow.cpp
  src/searchengine/nova/__init__.py
  src/searchengine/nova/fix_encoding.py
  src/searchengine/nova/helpers.py
  src/searchengine/nova/nova2.py
  src/searchengine/nova/nova2dl.py
  src/searchengine/nova/novaprinter.py
  src/searchengine/nova/socks.py
  src/searchengine/searchengine.qrc
  src/update_qrc_files.py
Labels: Search engine

#12124 Fix crash when renaming torrent contents
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/trackerlistwidget.cpp
  src/gui/rss/rsswidget.cpp
  src/gui/torrentcontenttreeview.cpp
  src/gui/transferlistwidget.cpp
Labels: GUI

#12083 Allow single app instance per configuration
  src/app/application.cpp
  src/app/application.h
  src/app/cmdoptions.h
  src/app/main.cpp
Labels: Core

#12138 Update Qt translations
  INSTALL
  dist/mac/Info.plist
  dist/qt-translations/qt_ar.qm
  dist/qt-translations/qt_bg.qm
  dist/qt-translations/qt_ca.qm
  dist/qt-translations/qt_cs.qm
  dist/qt-translations/qt_da.qm
  dist/qt-translations/qt_de.qm
  dist/qt-translations/qt_es.qm
  dist/qt-translations/qt_eu.qm
  dist/qt-translations/qt_fi.qm
  dist/qt-translations/qt_fr.qm
  dist/qt-translations/qt_he.qm
  dist/qt-translations/qt_hu.qm
  dist/qt-translations/qt_it.qm
  dist/qt-translations/qt_ja.qm
  dist/qt-translations/qt_ko.qm
  dist/qt-translations/qt_nl.qm
  dist/qt-translations/qt_pl.qm
  dist/qt-translations/qt_pt_BR.qm
  dist/qt-translations/qt_ru.qm
  dist/qt-translations/qt_sk.qm
  dist/qt-translations/qt_tr.qm
  dist/qt-translations/qt_uk.qm
  dist/qt-translations/qt_zh_CN.qm
  dist/qt-translations/qt_zh_TW.qm
  dist/qt-translations/qtbase_ar.qm
  dist/qt-translations/qtbase_bg.qm
  dist/qt-translations/qtbase_ca.qm
  dist/qt-translations/qtbase_cs.qm
  dist/qt-translations/qtbase_da.qm
  dist/qt-translations/qtbase_de.qm
  dist/qt-translations/qtbase_es.qm
  dist/qt-translations/qtbase_fi.qm
  dist/qt-translations/qtbase_gd.qm
  dist/qt-translations/qtbase_he.qm
  dist/qt-translations/qtbase_hu.qm
  dist/qt-translations/qtbase_it.qm
  dist/qt-translations/qtbase_ko.qm
  dist/qt-translations/qtbase_pl.qm
  dist/qt-translations/qtbase_ru.qm
  dist/qt-translations/qtbase_zh_TW.qm
  dist/windows/installer.nsi
  dist/windows/uninstaller.nsi
  macxconf.pri
  src/app/CMakeLists.txt
Labels: Translation

#12035 Move torrent storages one by one
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/gui/transferlistwidget.cpp
Labels: Core, Performance

#12158 Add man page files in Markdown format
  doc/README.md
  doc/qbittorrent-nox.1
  doc/qbittorrent-nox.1.md
  doc/qbittorrent.1
  doc/qbittorrent.1.md
Labels: Documentation

#12168 Get library version strings at runtime
  src/app/cmdoptions.cpp
  src/base/utils/misc.cpp
  src/gui/executionlogwidget.cpp
  src/gui/mainwindow.cpp
  src/gui/statusbar.cpp
  src/gui/tagfiltermodel.cpp
  src/gui/transferlistmodel.cpp
  src/webui/webapplication.h
Labels: Core

#12188 Append new move storage job to queue
  src/base/bittorrent/session.cpp
Labels: Hotfix

#12180 Fix total connected peers count calculation
  src/gui/statsdialog.cpp
  src/webui/api/synccontroller.cpp
Labels: Core

#12187 Allow other keypresses in LogListWidget
  src/gui/loglistwidget.cpp
Labels: GUI

#12206 Disable Auto TMM when not using default savepath from monitored folder
  src/base/scanfoldersmodel.cpp
Labels: Core

#12207 WebAPI: fix matching uncategorized torrents
  src/base/http/requestparser.cpp
  src/webui/api/torrentscontroller.cpp
Labels: WebAPI

#12154 NSIS: Add option to remove Windows path length limitation & Update manifest to support long path
  dist/windows/installer-translations/afrikaans.nsi
  dist/windows/installer-translations/albanian.nsi
  dist/windows/installer-translations/arabic.nsi
  dist/windows/installer-translations/basque.nsi
  dist/windows/installer-translations/belarusian.nsi
  dist/windows/installer-translations/bosnian.nsi
  dist/windows/installer-translations/breton.nsi
  dist/windows/installer-translations/bulgarian.nsi
  dist/windows/installer-translations/catalan.nsi
  dist/windows/installer-translations/croatian.nsi
  dist/windows/installer-translations/czech.nsi
  dist/windows/installer-translations/danish.nsi
  dist/windows/installer-translations/dutch.nsi
  dist/windows/installer-translations/english.nsi
  dist/windows/installer-translations/esperanto.nsi
  dist/windows/installer-translations/estonian.nsi
  dist/windows/installer-translations/farsi.nsi
  dist/windows/installer-translations/finnish.nsi
  dist/windows/installer-translations/french.nsi
  dist/windows/installer-translations/galician.nsi
  dist/windows/installer-translations/german.nsi
  dist/windows/installer-translations/greek.nsi
  dist/windows/installer-translations/hebrew.nsi
  dist/windows/installer-translations/hungarian.nsi
  dist/windows/installer-translations/icelandic.nsi
  dist/windows/installer-translations/indonesian.nsi
  dist/windows/installer-translations/irish.nsi
  dist/windows/installer-translations/italian.nsi
  dist/windows/installer-translations/japanese.nsi
  dist/windows/installer-translations/korean.nsi
  dist/windows/installer-translations/kurdish.nsi
  dist/windows/installer-translations/latvian.nsi
  dist/windows/installer-translations/lithuanian.nsi
  dist/windows/installer-translations/luxembourgish.nsi
  dist/windows/installer-translations/macedonian.nsi
  dist/windows/installer-translations/malay.nsi
  dist/windows/installer-translations/mongolian.nsi
  dist/windows/installer-translations/norwegian.nsi
  dist/windows/installer-translations/norwegiannynorsk.nsi
  dist/windows/installer-translations/polish.nsi
  dist/windows/installer-translations/portuguese.nsi
  dist/windows/installer-translations/portugueseBR.nsi
  dist/windows/installer-translations/romanian.nsi
  dist/windows/installer-translations/russian.nsi
  dist/windows/installer-translations/serbian.nsi
  dist/windows/installer-translations/serbianlatin.nsi
  dist/windows/installer-translations/simpchinese.nsi
  dist/windows/installer-translations/slovak.nsi
  dist/windows/installer-translations/slovenian.nsi
  dist/windows/installer-translations/spanish.nsi
  dist/windows/installer-translations/spanishinternational.nsi
  dist/windows/installer-translations/swedish.nsi
  dist/windows/installer-translations/thai.nsi
  dist/windows/installer-translations/tradchinese.nsi
  dist/windows/installer-translations/turkish.nsi
  dist/windows/installer-translations/ukrainian.nsi
  dist/windows/installer-translations/uzbek.nsi
  dist/windows/installer-translations/welsh.nsi
  dist/windows/installer.nsi
  src/qbittorrent.exe.manifest
Labels: NSIS, OS: Windows

#12260 Construct QString more efficiently
  src/app/application.cpp
  src/app/cmdoptions.cpp
  src/app/main.cpp
  src/app/stacktrace_win.h
  src/base/bittorrent/session.cpp
  src/base/http/responsegenerator.cpp
  src/base/net/geoipmanager.cpp
  src/base/net/proxyconfigurationmanager.cpp
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_autodownloadrule.cpp
  src/base/rss/rss_feed.cpp
  src/base/rss/rss_session.cpp
  src/base/search/searchpluginmanager.cpp
  src/gui/aboutdialog.cpp
  src/gui/advancedsettings.cpp
  src/gui/categoryfiltermodel.cpp
  src/gui/lineedit.cpp
  src/gui/mainwindow.cpp
  src/gui/optionsdialog.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/rss/feedlistwidget.cpp
  src/gui/statsdialog.cpp
  src/gui/tagfiltermodel.cpp
  src/gui/torrentcreatordialog.cpp
  src/gui/transferlistfilterswidget.cpp
  src/webui/api/apierror.h
  src/webui/api/searchcontroller.cpp
Labels: Code cleanup, Translation

#12273 Don't round scaling factor
  src/app/main.cpp
Labels: GUI, Hotfix

#12259 Rely on Qt ownership to free resources
  src/base/net/private/downloadhandlerimpl.cpp
  src/base/net/private/downloadhandlerimpl.h
Labels: Core

#12265 NSIS: Update Finnish translation
  dist/windows/installer-translations/finnish.nsi
Labels: Translation

#12269 NSIS: Update Japanese translation
  dist/windows/installer-translations/japanese.nsi
Labels: Translation

#12244 NSIS: Update Turkish translation
  dist/windows/installer-translations/turkish.nsi
Labels: Translation

#12283 Include translation resources with file globbing
  dist/windows/installer.nsi
  dist/windows/uninstaller.nsi
  macxconf.pri
  src/app/CMakeLists.txt
Labels: Build system, NSIS

#12285 Save log file in UTF-8 encoding
  src/app/filelogger.cpp
Labels: Core

#12291 NSIS: Update Russian translation
  dist/windows/installer-translations/russian.nsi
Labels: Translation

#12232 Add logging for SOCKS5 proxy errors
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
Labels: Core

#12299 Initialize struct variables
  src/base/net/private/geoipdatabase.cpp
Labels: Code cleanup

#12228 Added alt and title tags for WebUI footer
  src/webui/www/private/index.html
  src/webui/www/private/scripts/client.js
Labels: WebUI

#12175 Add UPnP lease duration advanced option
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: Core

#12282 Fix regression when fastresume contains network path
  src/base/bittorrent/session.cpp
Labels: Core, Hotfix

#12317 Fix broken UNC paths in fastresumes on Windows
  src/base/bittorrent/session.cpp
Labels: Hotfix

#12348 Prevent multiple instances for the same app config
  src/app/application.cpp
Labels: Core, Hotfix, OS: Windows
