Repository qbittorrent/qBittorrent, pull requests merged in 2020-04, with the labels that each got.

#12363 Fix unexpected torrent resume after app restart
  src/base/bittorrent/session.cpp
Labels: Core, Hotfix

#12350 Improve logging for errors
  src/base/bittorrent/private/resumedatasavingmanager.cpp
Labels: Core

#12372 Fix mismatch ID
  src/webui/www/private/views/installsearchplugin.html
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/search.html
  src/webui/www/private/views/searchplugins.html
Labels: WebUI

#12396 Fix sub-sorting of Transfer list
  src/gui/transferlistsortmodel.cpp
Labels: GUI, Hotfix

#12364 Avoid holding entire file in memory
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/torrentcreatorthread.cpp
  src/base/bittorrent/torrentinfo.cpp
  src/base/utils/io.cpp
  src/base/utils/io.h
Labels: Core

#12404 Fix wrong logic that disables "prevent sleeping" timer
  src/gui/mainwindow.cpp
  src/gui/powermanagement/powermanagement.cpp
  src/gui/powermanagement/powermanagement.h
Labels: Core

#12416 Set disk cache size for older libtorrent versions
  src/base/bittorrent/session.cpp
Labels: Core, Hotfix

#12420 Sort locale language list
  src/base/unicodestrings.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
Labels: Code cleanup

#12427 Avoid inefficient behavior
  src/base/utils/io.cpp
Labels: Core

#12382 Remove white outline around mascot.png
  src/icons/skin/mascot.png
Labels: Look and Feel

#12430 Fix outgoing interfaces not getting assigned in case addr is not null.
  src/base/bittorrent/session.cpp
Labels: Network

#12436 Save "resume data" when torrent storage is moved
  src/base/bittorrent/torrenthandle.cpp
Labels: Core, Hotfix

#12301 Better Python path detection on Windows
  src/base/utils/foreignapps.cpp
Labels: Search engine

#12450 Avoid holding encoded resume data in memory
  src/base/bittorrent/private/resumedatasavingmanager.cpp
  src/base/bittorrent/private/resumedatasavingmanager.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/gui/mainwindow.cpp
Labels: Core

#12449 Fix add multiple peers from webui
  src/webui/www/private/addpeers.html
Labels: WebUI

#12464 Fix date format for "Last seen complete"
  src/gui/transferlistmodel.cpp
Labels: GUI

#12423 Remove deprecated strict super seeding mode from advanced settings
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/webapplication.h
  src/webui/www/private/views/preferences.html
Labels: Core

#12484 Do not use 0.0.0.0 or [::] for outgoing interfaces
  src/base/bittorrent/session.cpp
Labels: Core, Hotfix

#12422 Change default stop_tracker_timeout settings
  src/base/bittorrent/session.cpp
Labels: Network

#12513 Split TorrentHandle interface and implementation
  src/app/application.cpp
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/peerinfo.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandle.h
  src/base/bittorrent/torrenthandleimpl.cpp
  src/base/bittorrent/torrenthandleimpl.h
  src/base/torrentfilter.cpp
  src/base/utils/fs.cpp
  src/gui/properties/piecesbar.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistsortmodel.cpp
  src/gui/transferlistwidget.cpp
  src/webui/api/serialize/serialize_torrent.cpp
  src/webui/api/synccontroller.cpp
Labels: Code cleanup, Core

#12538 TravisCI: Use libtorrent with deprecated functions disabled for Linux builds
  .travis.yml
  src/base/bittorrent/private/nativetorrentextension.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrentcreatorthread.cpp
  src/base/bittorrent/torrenthandleimpl.cpp
Labels: Build system

#12531 Add final specifier to classes
  src/app/application.h
  src/app/qtlocalpeer/qtlockedfile.h
  src/base/bittorrent/private/filterparserthread.h
  src/base/bittorrent/private/nativesessionextension.h
  src/base/bittorrent/private/nativetorrentextension.h
  src/base/bittorrent/private/portforwarderimpl.h
  src/base/bittorrent/torrentcreatorthread.h
  src/base/bittorrent/tracker.h
  src/base/http/server.h
  src/base/net/downloadmanager.cpp
  src/base/net/private/downloadhandlerimpl.h
  src/base/private/profile_p.h
  src/base/rss/private/rss_parser.cpp
  src/base/scanfoldersmodel.h
  src/webui/webapplication.h
Labels: Code cleanup

#12526 Change default upload slot choking limits
  src/base/bittorrent/session.cpp
Labels: Core

#12530 Reduce padding in structure
  src/base/logger.cpp
  src/base/logger.h
Labels: Core

#12545 Reduce padding in class
  src/base/bittorrent/torrenthandleimpl.cpp
  src/base/bittorrent/torrenthandleimpl.h
Labels: Code cleanup

#12544 Add final specifier to GUI classes
  src/gui/addnewtorrentdialog.h
  src/gui/autoexpandabledialog.h
  src/gui/categoryfiltermodel.h
  src/gui/categoryfilterproxymodel.h
  src/gui/categoryfilterwidget.h
  src/gui/cookiesdialog.h
  src/gui/cookiesmodel.h
  src/gui/fspathedit.h
  src/gui/hidabletabwidget.h
  src/gui/lineedit.h
  src/gui/log/logfiltermodel.h
  src/gui/log/loglistview.cpp
  src/gui/log/loglistview.h
  src/gui/mainwindow.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/previewlistdelegate.h
  src/gui/previewselectdialog.h
  src/gui/private/fspathedit_p.h
  src/gui/private/tristatewidget.h
  src/gui/properties/downloadedpiecesbar.h
  src/gui/properties/peerlistsortmodel.h
  src/gui/properties/peerlistwidget.h
  src/gui/properties/pieceavailabilitybar.h
  src/gui/properties/proplistdelegate.h
  src/gui/properties/speedplotview.h
  src/gui/properties/speedwidget.h
  src/gui/raisedmessagebox.h
  src/gui/rss/feedlistwidget.h
  src/gui/rss/htmlbrowser.h
  src/gui/scanfoldersdelegate.h
  src/gui/search/pluginselectdialog.h
  src/gui/search/searchjobwidget.h
  src/gui/search/searchlistdelegate.h
  src/gui/search/searchsortmodel.h
  src/gui/shutdownconfirmdialog.h
  src/gui/tagfiltermodel.h
  src/gui/tagfilterproxymodel.h
  src/gui/tagfilterwidget.h
  src/gui/torrentcontentfiltermodel.h
  src/gui/torrentcontentmodel.cpp
  src/gui/torrentcontentmodel.h
  src/gui/torrentcontentmodelfile.h
  src/gui/torrentcontentmodelfolder.h
  src/gui/torrentcontenttreeview.h
  src/gui/torrentcreatordialog.h
  src/gui/transferlistdelegate.h
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
  src/gui/transferlistmodel.h
  src/gui/transferlistsortmodel.h
  src/gui/transferlistwidget.h
  src/gui/updownratiodialog.h
Labels: Code cleanup

#12486 Update Info.plist
  dist/mac/Info.plist
Labels: OS: macOS

#12528 Don't uncheck Authentication checkbox when changing proxy type
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/webui/www/private/views/preferences.html
Labels: GUI, WebUI

#12567 Reduce ambiguity for selecting icons
  src/gui/optionsdialog.ui
Labels: Look and Feel

#12568 WebUI: Fix UPnP lease duration get/set
  src/webui/www/private/views/preferences.html
Labels: WebUI

#12487 Use configured net interface even when it is missing
  src/base/bittorrent/session.cpp
Labels: Network

#12598 NSIS: Update german translation
  dist/windows/installer-translations/german.nsi
Labels: NSIS, Translation

#12579 Add ability to send custom HTTP headers
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.ui
  src/webui/api/appcontroller.cpp
  src/webui/webapplication.cpp
  src/webui/webapplication.h
  src/webui/www/private/views/preferences.html
Labels: WebAPI

#12603 Fix crash when torrent is deleted on limit reached
  src/base/bittorrent/session.cpp
Labels: Core, Hotfix

#12549 Expand RSS related WebAPI
  src/webui/api/appcontroller.cpp
  src/webui/api/rsscontroller.cpp
  src/webui/api/rsscontroller.h
Labels: RSS, WebAPI

#12602 Register datatype properly
  src/base/bittorrent/session.h
Labels: Core, Hotfix

#12659 Fix typo in optionsdialog.cpp
  src/gui/optionsdialog.cpp
Labels: Look and Feel

#12655 Improve behavior of deleting torrents in transfer list
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
  src/webui/api/torrentscontroller.cpp
Labels: GUI

#12680 Switch TravisCI to bionic
  .travis.yml
Labels: Build system

#12637 NSIS: Updated Dutch translation
  dist/windows/installer-translations/dutch.nsi
Labels: Translation

#12480 CMake: Enforce minimum C++ mode support
  .travis.yml
  CMakeLists.txt
  cmake/Modules/FunctionQbtCXXCompilerAndModeCheck.cmake
  cmake/Modules/MacroQbtCompilerSettings.cmake
  src/CMakeLists.txt
Labels: Build system

#12176 Add HTTPS tracker certificate validation option
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: Core

#12691 Support range-based iteration in IndexRange class
  src/base/bittorrent/torrenthandleimpl.cpp
  src/base/http/httperror.h
  src/base/indexrange.h
  src/gui/previewselectdialog.h
  src/gui/rss/automatedrssdownloader.h
  src/webui/api/apierror.h
Labels: Core

#12692 Handle empty piece range properly
  src/base/bittorrent/torrenthandleimpl.cpp
  src/gui/torrentcontentmodel.cpp
  src/gui/torrentcontentmodelfile.cpp
Labels: Core
