Repository qbittorrent/qBittorrent, pull requests merged in 2020-09, with the labels that each got.

#13305 Fix "Open containing folder" opened the wrong path for folder item
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/propertieswidget.h
  src/gui/utils.cpp
Labels: GUI

#13328 Fix GeoDB download in systems with non-C locales
  src/base/net/geoipmanager.cpp
Labels: Core

#13337 Improve compatibility with libt 2.0
  src/base/bittorrent/filterparserthread.cpp
  src/base/bittorrent/session.cpp
Labels: Core

#13319 Expose libtorrent max_concurrent_http_announces in advanced settings
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: GUI, WebUI

#13336 Minor WebUI improvements
  src/base/http/types.h
  src/gui/gpl.html
  src/gui/thanks.html
  src/gui/translators.html
  src/webui/api/torrentscontroller.cpp
  src/webui/www/private/download.html
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/upload.html
  src/webui/www/public/scripts/login.js
Labels: Code cleanup, WebUI

#13340 Improve adding torrent using Magnet URI
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.h
Labels: Core

#13354 Disable deprecated settings in libtorrent 2.0
  src/base/bittorrent/session.cpp
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/www/private/views/preferences.html
Labels: Core

#13355 Enable faster disk space allocation by default
  src/base/bittorrent/session.cpp
Labels: Core

#13369 Avoid using libtorrent internal functions
  src/base/bittorrent/session.cpp
Labels: Core

#13268 Update minimum Python version to 3.5.0
  INSTALL
  src/base/utils/foreignapps.cpp
  src/gui/mainwindow.cpp
Labels: Search engine

#13366 Don't use HTML in Linux tray tooltip
  src/gui/mainwindow.cpp
Labels: GUI, OS: Linux

#13353 Fix peer blocked message
  src/base/bittorrent/session.cpp
  src/gui/log/logmodel.cpp
Labels: GUI

#13327 CMake: overhaul and improve scripts
  CMakeLists.txt
  cmake/Modules/CompileFeature.cmake
  cmake/Modules/DeployQt5.cmake
  cmake/Modules/FeatureOptionsSetup.cmake
  cmake/Modules/FindLibtorrentRasterbar.cmake
  cmake/Modules/FindSystemd.cmake
  cmake/Modules/FunctionQbtCXXCompilerAndModeCheck.cmake
  cmake/Modules/FunctionReadVersion.cmake
  cmake/Modules/MacroConfigureMSVCRuntime.cmake
  cmake/Modules/MacroLinkQtComponents.cmake
  cmake/Modules/MacroQbtCommonConfig.cmake
  cmake/Modules/MacroQbtCompilerSettings.cmake
  cmake/Modules/QbtTargetSources.cmake
  cmake/Modules/QbtTranslations.cmake
  cmake/Modules/bundle.cmake
  cmake/Modules/winconf-mingw.cmake
  cmake/Modules/winconf-msvc.cmake
  cmake/Modules/winconf.cmake
  dist/CMakeLists.txt
  dist/unix/CMakeLists.txt
  dist/windows/CMakeLists.txt
  src/CMakeLists.txt
  src/app/CMakeLists.txt
  src/base/CMakeLists.txt
  src/config.h.cmakein
  src/gui/CMakeLists.txt
  src/gui/rss/articlelistwidget.cpp
  src/webui/CMakeLists.txt
Labels: Build system, Discussion

#13388 Add missing semicolons in WebUI
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/views/rss.html
  src/webui/www/private/views/rssDownloader.html
Labels: Code cleanup, WebUI

#13390 Prevent peers from being lost when banning
  src/gui/properties/peerlistwidget.cpp
Labels: GUI

#13402 CMake: fix linking against OpenSSL
  src/base/CMakeLists.txt
Labels: Build system, Hotfix

#13399 Improvements to cmake build system
  cmake/Modules/MacroQbtCommonConfig.cmake
  src/CMakeLists.txt
Labels: Build system

#13400 Improve sequentialDownload/firstLastPiecePriority handling
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrenthandleimpl.cpp
  src/base/bittorrent/torrenthandleimpl.h
Labels: Core

#12577 Allow users to configure no_connect_privileged_ports
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: Core

#13412 CMake improvements
  cmake/Modules/MacroQbtCommonConfig.cmake
  src/app/CMakeLists.txt
Labels: Build system

#13419 Fix fully-qualified-moc-types clazy warning
  src/base/bittorrent/session.h
Labels: Code cleanup, Core

#13429 Fix building in macOS on TravisCI
  .travis.yml
  src/base/bittorrent/torrenthandleimpl.cpp
Labels: CI

#13288 Add GitHub Actions CI workflow
  .github/workflows/ci.yaml
Labels: CI

#13431 Fix code defects
  src/base/bittorrent/downloadpriority.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrenthandle.cpp
  src/base/bittorrent/torrenthandleimpl.cpp
  src/base/bittorrent/torrentinfo.cpp
  src/gui/updownratiodialog.cpp
Labels: Code cleanup

#13445 Use toned green color for downloading pieces in Pieces bar
  src/gui/properties/downloadedpiecesbar.cpp
  src/gui/properties/downloadedpiecesbar.h
Labels: GUI

#13456 Fix CMake project
  src/app/CMakeLists.txt
Labels: Build system

#13432 Add workflow status badge for GitHub Actions CI
  README.md
Labels: CI
