Repository qbittorrent/qBittorrent, pull requests merged in 2021-10, with the labels that each got.

#15505 Add detection for various OS
  configure
  configure.ac
Labels: Build system

#15509 Organizes ComboBox items in Behavior Preferences
  src/gui/optionsdialog.ui
Labels: GUI

#14465 Allow to build with Qt6
  CMakeLists.txt
  src/CMakeLists.txt
  src/app/CMakeLists.txt
  src/base/CMakeLists.txt
  src/gui/CMakeLists.txt
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
  src/src.pro
Labels: Core

#15468 Improve torrent content handling
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/abstractfilestorage.h
  src/base/bittorrent/lttypecast.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentcreatorthread.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/base/bittorrent/torrentinfo.cpp
  src/base/bittorrent/torrentinfo.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/previewselectdialog.cpp
  src/gui/torrentcontentmodel.cpp
  src/gui/torrentcontentmodelfolder.cpp
  src/gui/transferlistwidget.cpp
Labels: Core

#15511 Put PR template into action
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
  .github/pull_request_template.yml
  CONTRIBUTING.md
Labels: Project management

#15516 GHA CI: build dependencies manually
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_windows.yaml
  .github/workflows/coverity-scan.yml
Labels: CI

#15520 Fix various typos
  src/gui/transferlistsortmodel.cpp
  src/searchengine/nova3/socks.py
Labels: Code cleanup

#15644 Explicitly set "added time" when adding new torrent
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#15622 Revert "NSIS: Add Bengali translation"
  dist/windows/installer-translations/bengali.nsi
  dist/windows/translations.nsi
Labels: Translation, NSIS
