Repository qbittorrent/qBittorrent, pull requests merged in 2021-03, with the labels that each got.

#14423 Support sub-sorting in Transferlist
  src/gui/transferlistsortmodel.cpp
  src/gui/transferlistsortmodel.h
Labels: GUI

#14189 Raise minimum libtorrent version to 1.2.12 (2.0.2)
  .github/workflows/ci.yaml
  .travis.yml
  CMakeLists.txt
  INSTALL
  configure
  configure.ac
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  vcpkg/libtorrent/CONTROL
  vcpkg/libtorrent/no_use_iconv.patch
  vcpkg/libtorrent/portfile.cmake
  vcpkg/libtorrent/readme.md
Labels: Build system, CI, Code cleanup, Core

#14472 Correctly draw the background of progress bar
  src/gui/progressbardelegate.cpp
Labels: GUI

#14484 Properly stop torrent creation if aborted
  src/base/bittorrent/torrentcreatorthread.cpp
Labels: Core

#14491 Fix TravisCI macOS builds
  .travis.yml
  src/gui/mainwindow.cpp
Labels: CI

#14466 Improve "info hash" handling
  src/app/application.cpp
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/infohash.cpp
  src/base/bittorrent/infohash.h
  src/base/bittorrent/magneturi.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/tracker.cpp
  src/base/digest32.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/transferlistsortmodel.h
  src/gui/transferlistwidget.cpp
  src/webui/api/serialize/serialize_torrent.cpp
  src/webui/api/synccontroller.cpp
  src/webui/api/torrentscontroller.cpp
Labels: Code cleanup, Core

#14493 Expose ToS setting from libtorrent
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/rename_file.html
  src/webui/www/private/views/preferences.html
Labels: Core

#14505 Look for qbittorrent.pdb in installation directory
  src/app/stacktrace_win.h
Labels: Core, OS: Windows

#14519 Accept "share limits" when adding torrent using WebAPI
  src/base/utils/string.cpp
  src/base/utils/string.h
  src/webui/api/torrentscontroller.cpp
  src/webui/webapplication.h
Labels: WebAPI

#14479 Improve tracker entries handling
  src/base/bittorrent/magneturi.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentinfo.cpp
  src/base/bittorrent/torrentinfo.h
  src/base/bittorrent/trackerentry.cpp
  src/base/bittorrent/trackerentry.h
  src/gui/properties/trackerlistwidget.cpp
  src/gui/properties/trackersadditiondialog.cpp
  src/gui/trackerentriesdialog.cpp
  src/gui/trackerentriesdialog.h
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
  src/webui/api/synccontroller.cpp
  src/webui/api/torrentscontroller.cpp
Labels: Core

#14537 Properly show tracker status for "paused" torrents
  src/base/bittorrent/torrentimpl.cpp
Labels: Core, Hotfix

#14503 Improve "info hash" handling (step 2)
  .travis.yml
  src/app/application.cpp
  src/base/bittorrent/filesearcher.cpp
  src/base/bittorrent/filesearcher.h
  src/base/bittorrent/infohash.cpp
  src/base/bittorrent/infohash.h
  src/base/bittorrent/magneturi.cpp
  src/base/bittorrent/magneturi.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrent.cpp
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/base/bittorrent/torrentinfo.cpp
  src/base/bittorrent/torrentinfo.h
  src/base/bittorrent/tracker.cpp
  src/base/bittorrent/tracker.h
  src/base/torrentfilter.cpp
  src/base/torrentfilter.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/mainwindow.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/torrentoptionsdialog.cpp
  src/gui/torrentoptionsdialog.h
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
  src/gui/transferlistsortmodel.cpp
  src/gui/transferlistsortmodel.h
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
  src/webui/api/serialize/serialize_torrent.cpp
  src/webui/api/serialize/serialize_torrent.h
  src/webui/api/synccontroller.cpp
  src/webui/api/torrentscontroller.cpp
Labels: Core

#14525 Initialize torrent status from add torrent params
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#14516 Replace parameters in one step
  src/app/application.cpp
Labels: Core

#14427 Raise minimum Qt version to 5.12
  .github/workflows/ci.yaml
  CMakeLists.txt
  configure
  configure.ac
  m4/qbittorrent.m4
  src/app/CMakeLists.txt
  src/app/application.cpp
  src/app/main.cpp
  src/base/asyncfilestorage.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrentinfo.cpp
  src/base/preferences.cpp
  src/base/preferences.h
  src/base/rss/rss_parser.cpp
  src/base/utils/fs.cpp
  src/gui/autoexpandabledialog.cpp
  src/gui/log/loglistview.cpp
  src/gui/optionsdialog.cpp
  src/gui/properties/speedplotview.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/torrentcontentmodel.cpp
  src/webui/api/synccontroller.cpp
Labels: Code cleanup, Project management

#14547 Don't use deprecated QTextCodec
  src/base/net/smtp.cpp
  src/base/net/smtp.h
Labels: Code cleanup

#14540 Remember sub sort column of transfer list
  src/gui/transferlistsortmodel.cpp
  src/gui/transferlistsortmodel.h
Labels: GUI

#14520 Improve "save resume data" handling
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrentimpl.cpp
Labels: Code cleanup, Core

#14562 Show progress bar in disabled state for paused torrents
  INSTALL
  src/gui/transferlistdelegate.cpp
  src/gui/transferlistmodel.cpp
  src/gui/transferlistmodel.h
Labels: GUI

#14567 Clean up the code
  src/gui/mainwindow.cpp
  src/gui/torrentcontentmodelitem.cpp
  src/gui/utils.cpp
Labels: Code cleanup

#14554 Seeding time in WebUI
  src/webui/api/serialize/serialize_torrent.cpp
  src/webui/api/serialize/serialize_torrent.h
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/prop-general.js
Labels: WebUI

#14546 Use QRegularExpression instead of deprecated QRegExp
  src/app/qtlocalpeer/qtlocalpeer.cpp
  src/base/rss/rss_autodownloadrule.cpp
  src/base/rss/rss_parser.cpp
  src/base/utils/string.cpp
  src/base/utils/string.h
  src/gui/properties/propertieswidget.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/torrentcontentfiltermodel.cpp
  src/gui/transferlistwidget.cpp
  src/webui/webapplication.cpp
Labels: Code cleanup

#14576 Wrap "resume data" in LoadTorrentParams
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Code cleanup, Core

#14570 WebUI: Avoid decoding strings repeatedly
  src/webui/www/private/confirmfeeddeletion.html
  src/webui/www/private/confirmruleclear.html
  src/webui/www/private/confirmruledeletion.html
  src/webui/www/private/edittracker.html
  src/webui/www/private/rename.html
  src/webui/www/private/rename_file.html
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/setlocation.html
  src/webui/www/private/views/rss.html
  src/webui/www/private/views/rssDownloader.html
Labels: WebUI

#14504 Fix bad IPv6 address format for outgoingInterfaces
  src/base/bittorrent/session.cpp
Labels: Network

#14583 Correctly draw progress bar in Qt 6
  src/gui/progressbarpainter.cpp
Labels: GUI, Qt6 compat

#14587 Remove wrong parentheses in WebUI
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/download.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/file-tree.js
  src/webui/www/private/scripts/filesystem.js
  src/webui/www/private/scripts/preferences.js
  src/webui/www/private/scripts/progressbar.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/scripts/prop-general.js
  src/webui/www/private/scripts/prop-peers.js
  src/webui/www/private/scripts/prop-trackers.js
  src/webui/www/private/scripts/prop-webseeds.js
  src/webui/www/private/views/filters.html
  src/webui/www/private/views/installsearchplugin.html
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/rss.html
  src/webui/www/private/views/rssDownloader.html
  src/webui/www/private/views/search.html
  src/webui/www/private/views/searchplugins.html
  src/webui/www/private/views/transferlist.html
Labels: Hotfix, WebUI

#14586 Don't cause QHash relayout while using reference to its node
  src/base/rss/rss_parser.cpp
Labels: Code cleanup, Qt6 compat

#14581 Implement BencodeResumeDataStorage class
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/loadtorrentparams.h
  src/base/bittorrent/resumedatasavingmanager.cpp
  src/base/bittorrent/resumedatastorage.cpp
  src/base/bittorrent/resumedatastorage.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#14619 Sort invalid QDateTime values after valid values
  src/gui/transferlistsortmodel.cpp
Labels: GUI, Hotfix

#14590 Add WebUI checking to CI
  .github/workflows/webui_ci.yaml
  src/webui/www/.eslintrc.json
  src/webui/www/.jsbeautifyrc
  src/webui/www/package.json
  src/webui/www/private/addpeers.html
  src/webui/www/private/addtrackers.html
  src/webui/www/private/confirmdeletion.html
  src/webui/www/private/download.html
  src/webui/www/private/edittracker.html
  src/webui/www/private/index.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/scripts/speedslider.js
  src/webui/www/private/views/about.html
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/propertiesToolbar.html
  src/webui/www/private/views/rss.html
  src/webui/www/private/views/rssDownloader.html
  src/webui/www/private/views/search.html
  src/webui/www/private/views/searchplugins.html
  src/webui/www/public/index.html
Labels: Code cleanup, WebUI

#14625 Backport to v4_3_x (#14619, #14590)
  .github/workflows/webui_ci.yaml
  src/gui/transferlistsortmodel.cpp
  src/webui/www/.eslintrc.json
  src/webui/www/.jsbeautifyrc
  src/webui/www/package.json
  src/webui/www/private/addpeers.html
  src/webui/www/private/addtrackers.html
  src/webui/www/private/confirmdeletion.html
  src/webui/www/private/download.html
  src/webui/www/private/edittracker.html
  src/webui/www/private/index.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/scripts/speedslider.js
  src/webui/www/private/views/about.html
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/propertiesToolbar.html
  src/webui/www/private/views/rss.html
  src/webui/www/private/views/rssDownloader.html
  src/webui/www/private/views/search.html
  src/webui/www/private/views/searchplugins.html
  src/webui/www/public/index.html
Labels: Backport

#14624 Fix tabChangesFocus attribute in "Edit trackers" dialog
  src/gui/trackerentriesdialog.ui
Labels: GUI, Hotfix

#14628 Lower Qt requirement to 5.11
  CMakeLists.txt
  configure
  configure.ac
  m4/qbittorrent.m4
  src/app/CMakeLists.txt
  src/app/qtlocalpeer/qtlocalpeer.cpp
  src/base/rss/rss_autodownloadrule.cpp
  src/base/rss/rss_parser.cpp
  src/base/utils/string.cpp
  src/base/utils/string.h
  src/gui/properties/propertieswidget.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/torrentcontentfiltermodel.cpp
  src/gui/transferlistwidget.cpp
  src/webui/webapplication.cpp
Labels: Core

#14647 Move cursor to the next line of end of text
  src/gui/downloadfromurldialog.cpp
Labels: GUI

#14593 Make current codebase more compatible with Qt6
  src/app/filelogger.cpp
  src/app/main.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/net/reverseresolution.cpp
  src/base/net/reverseresolution.h
  src/base/settingsstorage.cpp
  src/gui/addnewtorrentdialog.cpp
  src/gui/properties/piecesbar.cpp
  src/gui/properties/piecesbar.h
  src/gui/properties/propertieswidget.cpp
  src/gui/torrentcontentmodel.cpp
Labels: Qt6 compat

#14637 Remove contributor as requested
  src/gui/translators.html
Labels: Project management

#14645 Remove unnecessary URL encoding
  src/webui/www/private/views/search.html
Labels: WebUI
