Repository qbittorrent/qBittorrent, pull requests merged in 2021-05, with the labels that each got.

#14861 Initialize struct members by default
  src/base/bittorrent/trackerentry.h
Labels: Code cleanup

#14714 Show priority menu at top level if there is no other
  src/gui/addnewtorrentdialog.cpp
Labels: GUI

#14895 NSIS: Update Japanese translation
  dist/windows/installer-translations/japanese.nsi
Labels: NSIS, OS: Windows, Translation

#14905 NSIS: Update Turkish translation
  dist/windows/installer-translations/turkish.nsi
Labels: NSIS, OS: Windows, Translation

#14909 GitHub Actions CI: update workflow
  .github/workflows/ci.yaml
  vcpkg/libtorrent/CONTROL
  vcpkg/libtorrent/no_use_iconv.patch
  vcpkg/libtorrent/portfile.cmake
  vcpkg/libtorrent/readme.md
Labels: CI

#14906 NSIS: Update Hungarian translation
  dist/windows/installer-translations/hungarian.nsi
Labels: NSIS, OS: Windows, Translation

#14927 Make some strings in WebUI translatable
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/rss.html
  src/webui/www/private/views/search.html
Labels: Translation, WebUI

#14928 Fix potential data race
  src/base/bittorrent/dbresumedatastorage.cpp
  src/base/settingsstorage.cpp
  src/gui/properties/piecesbar.cpp
  src/gui/properties/piecesbar.h
Labels: Code cleanup, Core

#14933 NSIS: Update Swedish translation
  dist/windows/installer-translations/swedish.nsi
Labels: NSIS, Translation

#14950 NSIS: Update Swedish translation
  dist/windows/installer-translations/swedish.nsi
Labels: NSIS, Translation

#14956 Fix typo "Highlited"
  src/gui/properties/piecesbar.cpp
Labels: Code cleanup

#14966 Bump file pool size
  src/base/bittorrent/session.cpp
Labels: Core

#14926 Add context menu for searchwidget to allow closing selected tab or all the tabs
  src/gui/search/searchwidget.cpp
  src/gui/search/searchwidget.h
Labels: GUI

#14983 Update AppVeyor CI image to Visual Studio 2019
  .appveyor.yml
Labels: CI, OS: Windows

#15001 Announce to all trackers if IP changed
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: Core

#14976 Add `connection_speed` to advanced settings
  src/base/bittorrent/dbresumedatastorage.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/http/types.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/api/serialize/serialize_torrent.h
  src/webui/webapplication.cpp
  src/webui/webapplication.h
  src/webui/www/private/views/preferences.html
Labels: Core, WebAPI

#14997 Remove the lockfile on exit
  src/app/qtlocalpeer/qtlocalpeer.cpp
  src/app/qtlocalpeer/qtlocalpeer.h
Labels: Core

#14934 Update Qt translations and add new qbt translations
  dist/qt-translations/qt_fa.qm
  dist/qt-translations/qt_gl.qm
  dist/qt-translations/qt_lt.qm
  dist/qt-translations/qt_pt.qm
  dist/qt-translations/qt_sl.qm
  dist/qt-translations/qt_zh_CN.qm
  dist/qt-translations/qtbase_ar.qm
  dist/qt-translations/qtbase_bg.qm
  dist/qt-translations/qtbase_ca.qm
  dist/qt-translations/qtbase_cs.qm
  dist/qt-translations/qtbase_da.qm
  dist/qt-translations/qtbase_de.qm
  dist/qt-translations/qtbase_es.qm
  dist/qt-translations/qtbase_fi.qm
  dist/qt-translations/qtbase_fr.qm
  dist/qt-translations/qtbase_gd.qm
  dist/qt-translations/qtbase_he.qm
  dist/qt-translations/qtbase_hu.qm
  dist/qt-translations/qtbase_it.qm
  dist/qt-translations/qtbase_ja.qm
  dist/qt-translations/qtbase_ko.qm
  dist/qt-translations/qtbase_lv.qm
  dist/qt-translations/qtbase_pl.qm
  dist/qt-translations/qtbase_ru.qm
  dist/qt-translations/qtbase_sk.qm
  dist/qt-translations/qtbase_tr.qm
  dist/qt-translations/qtbase_uk.qm
  dist/qt-translations/qtbase_zh_TW.qm
  src/base/unicodestrings.h
  src/gui/optionsdialog.cpp
  src/lang/lang.qrc
  src/lang/qbittorrent_fa.ts
  src/lang/qbittorrent_mn_MN.ts
  src/lang/qbittorrent_th.ts
  src/webui/www/private/views/preferences.html
  src/webui/www/translations/webui_fa.ts
  src/webui/www/translations/webui_mn_MN.ts
  src/webui/www/translations/webui_th.ts
  src/webui/www/translations/webui_translations.qrc
Labels: Translation

#15016 Update Mac icons for Big Sur
  dist/mac/qBitTorrentDocument.icns
  dist/mac/qbittorrent_mac.icns
  src/icons/qbittorrent_mac.svg
Labels: Look and Feel, OS: macOS

#14995 CMake: Fix compiler ID checks
  cmake/Modules/MacroQbtCommonConfig.cmake
Labels: Build system

#13934 CMake: fix MSVC __cplusplus
  cmake/Modules/MacroQbtCommonConfig.cmake
Labels: Build system, OS: Windows

#15017 Format and lint CSS code
  src/webui/www/.stylelintrc.json
  src/webui/www/package.json
  src/webui/www/private/css/Core.css
  src/webui/www/private/css/Layout.css
  src/webui/www/private/css/Tabs.css
  src/webui/www/private/css/Window.css
  src/webui/www/private/css/dynamicTable.css
  src/webui/www/private/css/style.css
  src/webui/www/public/css/login.css
Labels: CI, Code cleanup, WebUI

#14993 Provide correct error description in "upload mode"
  src/base/bittorrent/bencoderesumedatastorage.cpp
  src/base/bittorrent/bencoderesumedatastorage.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#15030 Update algorithm.h
  src/base/algorithm.h
Labels: Code cleanup

#15031 Fix main window turns blank after restoring from tray
  src/gui/mainwindow.cpp
Labels: GUI
