Repository qbittorrent/qBittorrent, pull requests merged in 2021-08, with the labels that each got.

#15251 Disconnect comment links fom the WebUI
  src/webui/www/private/scripts/misc.js
Labels: WebUI

#15242 Detect incompatible libtorrent v2 versions in build systems
  CMakeLists.txt
  INSTALL
  configure
  configure.ac
  m4/pkg.m4
  src/CMakeLists.txt
  src/app/qtlocalpeer/qtlockedfile_win.cpp
  src/app/stacktrace_win.h
Labels: Build system

#15247 Expose SSRF mitigation
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: Core, Libtorrent

#15262 NSIS: Add Polish translation
  dist/windows/installer-translations/polish.nsi
Labels: Translation

#15281 Update js libraries
  .github/workflows/file_health.sh
  src/webui/www/private/addpeers.html
  src/webui/www/private/addtrackers.html
  src/webui/www/private/confirmdeletion.html
  src/webui/www/private/confirmfeeddeletion.html
  src/webui/www/private/confirmruleclear.html
  src/webui/www/private/confirmruledeletion.html
  src/webui/www/private/download.html
  src/webui/www/private/downloadlimit.html
  src/webui/www/private/edittracker.html
  src/webui/www/private/index.html
  src/webui/www/private/newcategory.html
  src/webui/www/private/newfeed.html
  src/webui/www/private/newfolder.html
  src/webui/www/private/newrule.html
  src/webui/www/private/newtag.html
  src/webui/www/private/rename.html
  src/webui/www/private/rename_feed.html
  src/webui/www/private/rename_file.html
  src/webui/www/private/rename_rule.html
  src/webui/www/private/scripts/lib/MooTools-Core-1.6.0-compat-compressed.js
  src/webui/www/private/scripts/lib/MooTools-More-1.6.0-compat-compressed.js
  src/webui/www/private/scripts/lib/clipboard-2.0.0.min.js
  src/webui/www/private/scripts/lib/clipboard.min.js
  src/webui/www/private/scripts/lib/mocha-0.9.6-yc.js
  src/webui/www/private/scripts/lib/mocha.min.js
  src/webui/www/private/scripts/lib/mootools-1.2-core-yc.js
  src/webui/www/private/scripts/lib/mootools-1.2-more.js
  src/webui/www/private/setlocation.html
  src/webui/www/private/shareratio.html
  src/webui/www/private/upload.html
  src/webui/www/private/uploadlimit.html
  src/webui/www/webui.qrc
Labels: WebUI

#15264 WebUI: group trackers by hostname
  src/webui/www/private/scripts/client.js
Labels: WebUI

#15282 Delay processing of watched folders
  src/base/torrentfileswatcher.cpp
Labels: Hotfix, Core

#15297 Add compile definition to indicate using of libtorrent 2.0
  conf.pri.windows
  configure
  configure.ac
  src/CMakeLists.txt
  src/base/bittorrent/customstorage.cpp
  src/base/bittorrent/customstorage.h
  src/base/bittorrent/infohash.cpp
  src/base/bittorrent/infohash.h
  src/base/bittorrent/magneturi.cpp
  src/base/bittorrent/nativesessionextension.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrentcreatorthread.cpp
  src/base/bittorrent/torrentcreatorthread.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/base/bittorrent/torrentinfo.cpp
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/gui/downloadfromurldialog.cpp
  src/gui/statsdialog.cpp
  src/gui/torrentcreatordialog.cpp
  src/gui/torrentcreatordialog.h
Labels: Core

#15294 Accept v2 infohashes for download
  src/base/bittorrent/magneturi.cpp
Labels: Core

#15211 Introduce stale bot for PR
  .github/workflows/stale_bot.yaml
Labels: Project management

#15298 Run Coverity once per month
  .github/workflows/coverity-scan.yml
Labels: CI

#15305 Update README.md
  README.md
Labels: Project management

#15309 Fix cmake script
  cmake/Modules/MacroQbtCommonConfig.cmake
  src/CMakeLists.txt
Labels: Hotfix, Build system

#15315 Change IRC channel to Libera.Chat
  README.md
Labels: Documentation

#15310 Stale bot: Handle more PR per run
  .github/workflows/stale_bot.yaml
Labels: Project management

#15306 Minor UI revise
  src/gui/fspathedit.cpp
  src/gui/optionsdialog.ui
  src/webui/www/private/views/preferences.html
Labels: WebUI, GUI

#15321 Clean up workflow files coding style
  .github/workflows/ci.yaml
  .github/workflows/coverity-scan.yml
  .github/workflows/file_health.yaml
  .github/workflows/webui_ci.yaml
Labels: CI

#15340 Support libtorrent v2.0.4 in CI
  .github/workflows/ci.yaml
Labels: CI

#15339 Improve "last activity" calculation in WebAPI
  src/webui/api/serialize/serialize_torrent.cpp
Labels: WebAPI

#15342 GHA CI: Split "main CI" to multiple workflows
  .github/workflows/ci.yaml
  .github/workflows/ci_file_health.yaml
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_webui.yaml
  .github/workflows/ci_windows.yaml
Labels: CI

#15355 GHA CI: Use preinstalled vcpkg
  .github/workflows/ci_windows.yaml
Labels: CI

#15361 GHA CI: Backport latest changes
  .github/workflows/ci.yaml
  .github/workflows/ci_file_health.yaml
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_webui.yaml
  .github/workflows/ci_windows.yaml
  .github/workflows/file_health.yaml
  .github/workflows/webui_ci.yaml
Labels: Backport

#15357 Fix minor licensing issue
  CMakeLists.txt
  COPYING
Labels: Project management

#15356 Use "old file path" provided by libtorrent
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#15380 Update korean.nsi
  dist/windows/installer-translations/korean.nsi
Labels: Translation, NSIS

#15387 Remove unnecessary UI properties in "Add new torrent" dialog
  src/gui/addnewtorrentdialog.ui
Labels: GUI

#15394 Remove Windows Vista support from manifest
  src/qbittorrent.exe.manifest
Labels: OS: Windows, Code cleanup

#15395 Fix WebUI crash when tracker URL is invalid
  src/webui/www/private/scripts/client.js
Labels: WebUI, Hotfix
