Repository qbittorrent/qBittorrent, pull requests merged in 2021-01, with the labels that each got.

#14005 Bump project requirement to C++17
  .github/workflows/ci.yaml
  .travis.yml
  cmake/Modules/MacroQbtCommonConfig.cmake
  configure
  configure.ac
  m4/qbittorrent.m4
  src/app/qtlocalpeer/qtlocalpeer.cpp
  src/base/algorithm.h
  src/base/bittorrent/common.h
  src/base/bittorrent/ltunderlyingtype.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrenthandleimpl.cpp
  src/base/indexrange.h
  src/base/settingvalue.h
  src/base/tristatebool.h
  src/base/utils/io.cpp
  src/base/utils/io.h
  src/base/utils/string.h
  src/gui/advancedsettings.cpp
  winconf.pri
Labels: Core

#14094 Migrate away from deprecated `AC_OUTPUT` macro
  .github/workflows/file_health.sh
  configure
  configure.ac
Labels: Build system

#14108 Update "Keep top-level folder" in WebUI options
  src/webui/www/private/views/preferences.html
Labels: Hotfix, WebUI

#14118 Move parsing of TriStateBool to a static class function
  src/base/tristatebool.cpp
  src/base/tristatebool.h
  src/base/utils/string.cpp
  src/base/utils/string.h
  src/webui/api/torrentscontroller.cpp
Labels: Code cleanup

#14116 Drop notification about move storage finished
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
Labels: GUI

#14123 Don't re-check "missing files" torrents when re-start
  src/base/bittorrent/torrenthandleimpl.cpp
  src/base/bittorrent/torrenthandleimpl.h
Labels: Core

#14121 Improve load data behavior of SettingsStorage class
  src/app/application.cpp
  src/app/upgrade.cpp
  src/base/bittorrent/portforwarderimpl.cpp
  src/base/net/proxyconfigurationmanager.cpp
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_session.cpp
  src/base/settingsstorage.cpp
  src/base/settingsstorage.h
  src/base/settingvalue.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/cookiesdialog.cpp
  src/gui/mainwindow.cpp
Labels: Core

#14074 Remember dialog sizes
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/aboutdialog.cpp
  src/gui/aboutdialog.h
  src/gui/banlistoptionsdialog.cpp
  src/gui/banlistoptionsdialog.h
  src/gui/downloadfromurldialog.cpp
  src/gui/downloadfromurldialog.h
  src/gui/ipsubnetwhitelistoptionsdialog.cpp
  src/gui/ipsubnetwhitelistoptionsdialog.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/previewselectdialog.cpp
  src/gui/search/pluginselectdialog.cpp
  src/gui/search/pluginselectdialog.h
  src/gui/search/pluginsourcedialog.cpp
  src/gui/search/pluginsourcedialog.h
  src/gui/speedlimitdialog.cpp
  src/gui/speedlimitdialog.h
  src/gui/statsdialog.cpp
  src/gui/statsdialog.h
  src/gui/torrentcreatordialog.cpp
  src/gui/torrentoptionsdialog.cpp
  src/gui/torrentoptionsdialog.h
  src/gui/trackerentriesdialog.cpp
Labels: GUI

#14140 Use nested namespaces definition syntax
  src/base/utils/bytearray.h
  src/base/utils/foreignapps.h
  src/base/utils/fs.h
  src/base/utils/gzip.h
  src/base/utils/io.h
  src/base/utils/misc.h
  src/base/utils/net.h
  src/base/utils/password.h
  src/base/utils/random.h
  src/base/utils/string.h
Labels: Code cleanup

#14137 Use std::optional for optional parameters
  src/app/application.cpp
  src/app/cmdoptions.cpp
  src/app/cmdoptions.h
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/addtorrentparams.h
  src/base/bittorrent/session.cpp
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_autodownloadrule.cpp
  src/base/rss/rss_autodownloadrule.h
  src/base/scanfoldersmodel.cpp
  src/base/tristatebool.cpp
  src/base/tristatebool.h
  src/base/utils/string.cpp
  src/base/utils/string.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/torrentcreatordialog.cpp
  src/webui/api/logcontroller.cpp
  src/webui/api/rsscontroller.cpp
  src/webui/api/searchcontroller.cpp
  src/webui/api/torrentscontroller.cpp
Labels: Code cleanup, Core

#14138 Use single parameter to accept torrent source
  macxconf.pri
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
Labels: Code cleanup, Core

#14145 Generate version header when configuring project
  .gitignore
  CMakeLists.txt
  cmake/Modules/MacroQbtCommonConfig.cmake
  src/app/CMakeLists.txt
  src/app/application.cpp
  src/app/main.cpp
  src/app/stacktracedialog.cpp
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrentcreatorthread.cpp
  src/base/net/dnsupdater.cpp
  src/base/version.h.in
  src/gui/aboutdialog.cpp
  src/gui/mainwindow.cpp
  src/gui/programupdater.cpp
  src/qbittorrent.rc
  src/webui/api/appcontroller.cpp
  version.pri
Labels: Build system

#14157 Correctly set items flags in TorrentContentModel
  src/gui/torrentcontentmodel.cpp
Labels: GUI

#14166 Remove redundant suffix from TorrentHandle class name
  src/app/application.cpp
  src/app/application.h
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/addtorrentparams.h
  src/base/bittorrent/peerinfo.cpp
  src/base/bittorrent/peerinfo.h
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrent.cpp
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/base/torrentfilter.cpp
  src/base/torrentfilter.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/categoryfiltermodel.cpp
  src/gui/categoryfiltermodel.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/previewselectdialog.cpp
  src/gui/previewselectdialog.h
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/peerlistwidget.h
  src/gui/properties/piecesbar.cpp
  src/gui/properties/piecesbar.h
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/propertieswidget.h
  src/gui/properties/proplistdelegate.cpp
  src/gui/properties/trackerlistwidget.cpp
  src/gui/properties/trackerlistwidget.h
  src/gui/properties/trackersadditiondialog.cpp
  src/gui/properties/trackersadditiondialog.h
  src/gui/statsdialog.cpp
  src/gui/tagfiltermodel.cpp
  src/gui/tagfiltermodel.h
  src/gui/torrentcontenttreeview.cpp
  src/gui/torrentcontenttreeview.h
  src/gui/torrentcreatordialog.cpp
  src/gui/torrentoptionsdialog.cpp
  src/gui/torrentoptionsdialog.h
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
  src/gui/transferlistmodel.cpp
  src/gui/transferlistmodel.h
  src/gui/transferlistsortmodel.cpp
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
  src/webui/api/serialize/serialize_torrent.cpp
  src/webui/api/serialize/serialize_torrent.h
  src/webui/api/synccontroller.cpp
  src/webui/api/torrentscontroller.cpp
Labels: Code cleanup, Core

#14170 Use c++1z to enable c++17
  configure
  configure.ac
Labels: Build system

#14179 On Linux use legacy 'data' directory only as a fallback
  src/base/profile_p.cpp
Labels: Core, OS: Linux

#14176 Add script for generating project tarball
  CMakeLists.txt
  build_dist.sh
  qbittorrent.pro
  src/base/version.h.in
  version.pri
Labels: Build system

#14162 Disable compiler flags
  .github/workflows/ci.yaml
  cmake/Modules/MacroQbtCommonConfig.cmake
  src/base/unicodestrings.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/log/logmodel.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/rss/rsswidget.cpp
  src/gui/transferlistmodel.cpp
  src/src.pro
  winconf.pri
Labels: Build system, Code cleanup

#14198 Add README.md to searchengine folder
  src/searchengine/README.md
Labels: Project management

#14210 WebUI: Correctly represent torrent content structure
  src/webui/www/private/scripts/prop-files.js
Labels: Hotfix, WebUI

#14229 Improve detection of file extension string
  src/base/utils/fs.cpp
  src/gui/autoexpandabledialog.cpp
Labels: Code cleanup

#14240 Drop extension from generated content folder name
  src/base/bittorrent/torrentinfo.cpp
Labels: Core

#14233 Add ability to prioritize selected items by shown file order
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.ui
  src/gui/categoryfilterwidget.cpp
  src/gui/executionlogwidget.cpp
  src/gui/mainwindow.cpp
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/propertieswidget.ui
  src/gui/properties/trackerlistwidget.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/tagfilterwidget.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistwidget.cpp
Labels: Code cleanup, GUI

#14237 Allow tab to escape the text box in "Edit trackers" dialog
  src/gui/trackerentriesdialog.ui
Labels: GUI

#14242 Change title of "version update" dialog box
  src/gui/mainwindow.cpp
Labels: GUI

#14257 Validate HTTPS Tracker Certificate by default
  src/base/bittorrent/session.cpp
Labels: Core

#14256 Don't let "program update" dialog steal focus
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/optionsdialog.cpp
  src/gui/properties/propertieswidget.cpp
Labels: GUI

#12318 Translating new phrases
  dist/windows/installer-translations/czech.nsi
Labels: Translation

#12376 Update Portuguese BR NSIS translation
  dist/windows/installer-translations/portugueseBR.nsi
Labels: Translation

#14275 Bump WebAPI version
  src/webui/webapplication.h
Labels: Hotfix, WebAPI

#14292 Disable expand on double click in TorrentContentTreeView
  src/gui/torrentcontenttreeview.cpp
Labels: GUI

#14274 Improve behavior when using ProgramUpdater class
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/programupdater.cpp
  src/gui/programupdater.h
Labels: OS: Windows, OS: macOS
