Repository qbittorrent/qBittorrent, pull requests merged in 2021-11, with the labels that each got.

#15604 Fix torrent content sorting
  src/gui/properties/propertieswidget.cpp
Labels: GUI

#15661 Don't use deprecated statfs64() on macOS
  cmake/Modules/MacroQbtCommonConfig.cmake
  macxconf.pri
  src/base/utils/fs.cpp
Labels: OS: macOS, Code cleanup

#15653 NSIS: Update Simplified Chinese translation
  dist/windows/installer-translations/simpchinese.nsi
Labels: Translation, NSIS

#15648 Create lock file in config folder instead of temp folder
  src/app/application.cpp
  src/app/applicationinstancemanager.cpp
  src/app/applicationinstancemanager.h
  src/app/qtlocalpeer/qtlocalpeer.cpp
  src/app/qtlocalpeer/qtlocalpeer.h
  src/app/qtlocalpeer/qtlockedfile.h
  src/base/profile_p.cpp
Labels: Core

#15662 Optimize PNG images losslessly with FileOptimizer
  dist/unix/menuicons/128x128/apps/qbittorrent.png
  dist/unix/menuicons/128x128/status/qbittorrent-tray.png
  dist/unix/menuicons/16x16/apps/qbittorrent.png
  dist/unix/menuicons/16x16/status/qbittorrent-tray.png
  dist/unix/menuicons/192x192/apps/qbittorrent.png
  dist/unix/menuicons/192x192/status/qbittorrent-tray.png
  dist/unix/menuicons/22x22/apps/qbittorrent.png
  dist/unix/menuicons/22x22/status/qbittorrent-tray.png
  dist/unix/menuicons/24x24/apps/qbittorrent.png
  dist/unix/menuicons/24x24/status/qbittorrent-tray.png
  dist/unix/menuicons/32x32/apps/qbittorrent.png
  dist/unix/menuicons/32x32/status/qbittorrent-tray.png
  dist/unix/menuicons/36x36/apps/qbittorrent.png
  dist/unix/menuicons/36x36/status/qbittorrent-tray.png
  dist/unix/menuicons/48x48/apps/qbittorrent.png
  dist/unix/menuicons/48x48/status/qbittorrent-tray.png
  dist/unix/menuicons/64x64/apps/qbittorrent.png
  dist/unix/menuicons/64x64/status/qbittorrent-tray.png
  dist/unix/menuicons/72x72/apps/qbittorrent.png
  dist/unix/menuicons/72x72/status/qbittorrent-tray.png
  dist/unix/menuicons/96x96/apps/qbittorrent.png
  dist/unix/menuicons/96x96/status/qbittorrent-tray.png
  src/icons/loading.png
  src/icons/mascot.png
  src/icons/sphere2.png
  src/icons/splash.png
  src/webui/www/public/images/qbittorrent32.png
Labels: Look and feel

#15683 GHA CI: Revise artifact folder layout
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_windows.yaml
Labels: CI

#15693 Migrate away from low-level `SettingsStorage` class
  src/app/application.cpp
  src/app/application.h
  src/base/bittorrent/portforwarderimpl.cpp
  src/base/bittorrent/portforwarderimpl.h
  src/base/net/proxyconfigurationmanager.cpp
  src/base/net/proxyconfigurationmanager.h
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_autodownloader.h
  src/base/rss/rss_session.cpp
  src/base/rss/rss_session.h
  src/base/settingsstorage.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/watchedfolderoptionsdialog.cpp
Labels: Code cleanup

#15654 Add more download options to torrent search result right-click menu
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
Labels: Search engine, GUI

#15682 Store Qt6 table header states under a different key
  src/app/qtlocalpeer/qtlocalpeer.cpp
  src/app/qtlocalpeer/qtlocalpeer.h
  src/app/qtlocalpeer/qtlockedfile.cpp
  src/app/qtlocalpeer/qtlockedfile.h
  src/app/qtlocalpeer/qtlockedfile_unix.cpp
  src/app/qtlocalpeer/qtlockedfile_win.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/preferences.cpp
  src/base/utils/misc.cpp
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.h
  src/gui/cookiesdialog.cpp
  src/gui/cookiesdialog.h
  src/gui/previewselectdialog.cpp
Labels: Qt6 compat

#15717 WebUI: Remove IRC in about page
  README.md
  src/webui/www/private/views/about.html
Labels: WebUI

#15452 Move some options from transfer list's context menu into "Torrent options" dialog
  src/gui/torrentoptionsdialog.cpp
  src/gui/torrentoptionsdialog.h
  src/gui/torrentoptionsdialog.ui
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
Labels: GUI

#15740 Properly check if file priority changes
  src/gui/torrentcontentmodel.cpp
Labels: GUI

#15739 Apply download priority immediately in torrent content view
  src/gui/properties/proplistdelegate.cpp
Labels: GUI

#15727 Update AppVeyor CI image to Visual Studio 2022
  .appveyor.yml
Labels: CI

#15745 Revert "Use percentage notation for alpha-values in CSS"
  src/webui/www/private/css/Window.css
Labels: WebUI, Hotfix

#15749 GHA CI: Simplify commands
  .appveyor.yml
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_windows.yaml
  .github/workflows/coverity-scan.yml
Labels: CI

#15762 GHA CI: Use prebuilt Qt library
  .appveyor.yml
  .github/workflows/ci_windows.yaml
Labels: CI

#15757 Fix handling when Content-Length field is absent
  src/base/http/requestparser.cpp
Labels: Network, WebAPI

#15774 Store Qt6 table header states under a different key
  src/gui/addnewtorrentdialog.cpp
Labels: GUI

#15796 Fix defects found by clazy
  src/base/bittorrent/infohash.h
  src/base/bittorrent/ltqhash.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/digest32.h
  src/base/utils/misc.cpp
  src/base/utils/version.h
  src/gui/categoryfiltermodel.cpp
  src/gui/fspathedit.h
Labels: Code cleanup
