Repository qbittorrent/qBittorrent, pull requests merged in 2021-12, with the labels that each got.

#15799 Fix Korean locale string value
  src/base/unicodestrings.h
  src/webui/www/private/views/preferences.html
Labels: Translation

#15800 Store enum type in settings directly
  src/app/upgrade.cpp
  src/base/bittorrent/bandwidthscheduler.cpp
  src/base/net/dnsupdater.cpp
  src/base/net/dnsupdater.h
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/mainwindow.cpp
  src/gui/optionsdialog.cpp
  src/webui/api/appcontroller.cpp
  src/webui/api/synccontroller.cpp
Labels: Core

#15787 Disable "add peers" menu item instead of hiding it
  src/gui/properties/peerlistwidget.cpp
  src/webui/www/private/index.html
Labels: GUI

#15814 GHA CI: include translation file generation in test
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_windows.yaml
Labels: CI

#15812 Remove redundant layer of `QVariant` in `Preferences` class
  src/base/preferences.cpp
  src/base/preferences.h
Labels: Core

#15816 Make meaning of "torrent root path" consistent
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#15819 GHA CI: Update libtorrent version(s)
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_windows.yaml
  .github/workflows/coverity-scan.yml
Labels: CI

#15811 Introduce versioning on main configuration file
  src/app/upgrade.cpp
  src/base/preferences.cpp
  src/base/settingsstorage.h
  src/base/utils/version.h
  src/webui/www/private/views/preferences.html
Labels: Core

#15829 Simplify tray icon related code
  .github/workflows/ci_windows.yaml
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/uithememanager.cpp
  src/gui/uithememanager.h
Labels: GUI

#15831 Improvements for WebAPI server
  src/base/http/connection.cpp
  src/base/http/connection.h
  src/base/http/responsegenerator.cpp
Labels: Network

#15847 Use correct URL scheme when https is enabled
  src/app/application.cpp
Labels: WebUI

#15849 Don't expire connection when there are data in buffer
  src/base/http/connection.cpp
Labels: Network

#15853 Add "Show torrent options" double-click action
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/optionsdialog.ui
  src/gui/transferlistwidget.cpp
Labels: GUI

#15870 GHA CI: Don't upload built artifacts for dynamic linking builds
  .github/workflows/ci_ubuntu.yaml
Labels: CI

#15883 Fix garbage message when reporting error
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#15884 Migrate "setting key mappings" to upgrade code
  src/app/main.cpp
  src/app/upgrade.cpp
  src/app/upgrade.h
  src/base/settingsstorage.cpp
Labels: Core
