Repository qbittorrent/qBittorrent, pull requests merged in 2022-05, with the labels that each got.

#16951 Reduce the number of hashing threads by default
  src/base/bittorrent/session.cpp
Labels: Core

#16955 Reduce the number of hashing threads by default (Backport)
  src/base/bittorrent/session.cpp
Labels: Core, Backport

#16953 Move system signal related functions to its own file
  src/app/CMakeLists.txt
  src/app/app.pri
  src/app/main.cpp
  src/app/signalhandler.cpp
  src/app/signalhandler.h
Labels: Code cleanup

#16678 Prevent the new update box from blocking input on other dialogues
  src/gui/mainwindow.cpp
Labels: GUI

#16957 Prevent the new update box from blocking input on other dialogues
  src/gui/mainwindow.cpp
Labels: Backport

#16971 Move stacktrace dialog to gui folder
  src/app/CMakeLists.txt
  src/app/app.pri
  src/app/signalhandler.cpp
  src/app/stacktracedialog.ui
  src/base/bittorrent/torrentimpl.cpp
  src/gui/CMakeLists.txt
  src/gui/gui.pri
  src/gui/stacktracedialog.cpp
  src/gui/stacktracedialog.h
  src/gui/stacktracedialog.ui
Labels: Code cleanup

#16972 Separate docker image `data` and `config` dirs
  dist/docker/Dockerfile
  dist/docker/Readme.md
  dist/docker/entrypoint.sh
Labels: Docker

#16698 Increase limit of maximum number of articles per feed
  src/gui/optionsdialog.ui
Labels: RSS, GUI

#16978 Fix empty selection in WebUI language combobox
  src/webui/www/private/views/preferences.html
Labels: WebUI

#16977 Store WebUI port setting in human readable number
  src/base/preferences.cpp
  src/webui/api/appcontroller.cpp
Labels: Core

#16974 Fix Docker legal notice when using existing config
  dist/docker/entrypoint.sh
Labels: Docker

#16968 Add support for exporting .torrent from WebUI
  src/webui/api/apicontroller.cpp
  src/webui/api/apicontroller.h
  src/webui/api/torrentscontroller.cpp
  src/webui/api/torrentscontroller.h
  src/webui/webapplication.cpp
  src/webui/webapplication.h
  src/webui/www/private/index.html
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/views/transferlist.html
Labels: WebUI

#16976 Improve Docker build
  dist/docker/Dockerfile
  dist/docker/Readme.md
  dist/docker/entrypoint.sh
Labels: Docker

#16986 Bump boost requirement to 1.71
  CMakeLists.txt
  INSTALL
  configure
  configure.ac
Labels: Project management

#16987 Improve docker script
  dist/docker/Dockerfile
  dist/docker/Readme.md
  dist/docker/entrypoint.sh
Labels: Docker

#16992 Add script for docker-compose
  dist/docker/.env
  dist/docker/Dockerfile
  dist/docker/Readme.md
  dist/docker/docker-compose.yml
Labels: Docker

#17004 Improve compatiability with various platforms
  src/app/application.cpp
  src/base/utils/foreignapps.cpp
  src/gui/torrentcontentmodel.cpp
Labels: Code cleanup

#16988 Improve keyboard navigation
  src/gui/transferlistwidget.cpp
Labels: GUI

#17008 Mark all files as complete if torrent is in "seed mode"
  src/base/bittorrent/torrentimpl.cpp
Labels: Hotfix, Core

#17009 Preserve "skip hash check" when there is no metadata
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#17013 Use uniform way to export .torrent files
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#17018 Add trackers in exported .torrent files
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/base/bittorrent/torrentinfo.cpp
  src/base/bittorrent/torrentinfo.h
Labels: Core, Backport

#17022 Use stacktrace dialog when GUI is enabled
  src/app/signalhandler.cpp
Labels: GUI, Core

#17023 Improve logic when interfacing settings with combobox
  src/gui/advancedsettings.cpp
Labels: Code cleanup

#17045 Fix compilation with qmake
  src/base/utils/net.cpp
  src/gui/gui.pri
Labels: Hotfix, Code cleanup, Build system

#17046 WebUI: enforce coding style
  src/webui/www/.eslintrc.json
  src/webui/www/private/addpeers.html
  src/webui/www/private/downloadlimit.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/scripts/preferences.js
  src/webui/www/private/scripts/progressbar.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/scripts/prop-peers.js
  src/webui/www/private/scripts/prop-trackers.js
  src/webui/www/private/scripts/speedslider.js
  src/webui/www/private/uploadlimit.html
  src/webui/www/private/views/about.html
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/rss.html
  src/webui/www/private/views/rssDownloader.html
  src/webui/www/private/views/search.html
Labels: WebUI

#17042 Update space label when changing priorities in new torrent dialog
  src/gui/torrentcontentmodel.cpp
Labels: GUI

#16965 Consider brackets within wildcard as regular characters
  src/base/utils/string.cpp
Labels: GUI, Core

#17031 Fix wrong GUI behavior in "Optional IP address to bind to" setting
  src/base/net/geoipdatabase.cpp
  src/base/net/geoipdatabase.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
Labels: GUI, Code cleanup

#17058 Fix wrong GUI behavior in "Optional IP address to bind to" setting (backport)
  src/gui/advancedsettings.cpp
Labels: Backport

#17060 Consistently emit signal when file "ignored" state is changed
  src/gui/torrentcontentmodel.cpp
Labels: GUI, Backport

#17057 Disable copy, move constructors when inheriting from QObject
  cmake/Modules/MacroQbtCommonConfig.cmake
  src/base/net/dnsupdater.h
  src/base/net/smtp.h
  src/base/preferences.h
  src/base/rss/rss_parser.h
  src/base/settingsstorage.h
  src/gui/autoexpandabledialog.h
  src/gui/categoryfiltermodel.h
  src/gui/cookiesdialog.h
  src/gui/cookiesmodel.h
  src/gui/deletionconfirmationdialog.h
  src/gui/executionlogwidget.h
  src/gui/fspathedit.h
  src/gui/fspathedit_p.h
  src/gui/lineedit.h
  src/gui/mainwindow.h
  src/gui/powermanagement/powermanagement.h
  src/gui/powermanagement/powermanagement_x11.h
  src/gui/properties/peerlistwidget.h
  src/gui/properties/peersadditiondialog.h
  src/gui/properties/pieceavailabilitybar.h
  src/gui/properties/piecesbar.h
  src/gui/properties/speedplotview.h
  src/gui/properties/speedwidget.h
  src/gui/properties/trackersadditiondialog.h
  src/gui/rss/articlelistwidget.h
  src/gui/rss/feedlistwidget.h
  src/gui/rss/htmlbrowser.h
  src/gui/rss/rsswidget.h
  src/gui/shutdownconfirmdialog.h
  src/gui/tagfiltermodel.h
  src/gui/tagfilterwidget.h
  src/gui/torrentcontentfiltermodel.h
  src/src.pro
Labels: Code cleanup

#17064 Handle all "fastresume rejected" cases consistently
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#17073 Update clipboard.js to v2.0.11
  src/webui/www/private/scripts/lib/clipboard.min.js
Labels: WebUI

#17077 Sync flag icons with upstream
  src/icons/flags/ac.svg
  src/icons/flags/as.svg
  src/icons/flags/au.svg
  src/icons/flags/cp.svg
  src/icons/flags/de.svg
  src/icons/flags/dg.svg
  src/icons/flags/fr.svg
  src/icons/flags/gf.svg
  src/icons/flags/gp.svg
  src/icons/flags/gs.svg
  src/icons/flags/gu.svg
  src/icons/flags/hm.svg
  src/icons/flags/hn.svg
  src/icons/flags/io.svg
  src/icons/flags/kg.svg
  src/icons/flags/kr.svg
  src/icons/flags/kz.svg
  src/icons/flags/lb.svg
  src/icons/flags/mf.svg
  src/icons/flags/mg.svg
  src/icons/flags/my.svg
  src/icons/flags/nc.svg
  src/icons/flags/pm.svg
  src/icons/flags/pn.svg
  src/icons/flags/se.svg
  src/icons/flags/sh.svg
  src/icons/flags/sm.svg
  src/icons/flags/ta.svg
  src/icons/flags/tc.svg
  src/icons/flags/ua.svg
  src/icons/flags/vg.svg
  src/icons/flags/wf.svg
  src/icons/flags/yt.svg
Labels: GUI

#17087 Pause torrent in all "fastresume rejected" cases
  src/base/bittorrent/nativesessionextension.cpp
Labels: Core

#17097 Update torrent status filter counters consistently
  src/base/torrentfilter.cpp
  src/gui/transferlistfilterswidget.cpp
Labels: GUI

#17096 Initialize torrent status using libtorrent extension
  src/base/bittorrent/extensiondata.h
  src/base/bittorrent/nativetorrentextension.cpp
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#17120 Don't decompress the reply data for Qt 6.3
  src/base/net/downloadhandlerimpl.cpp
Labels: Network, Core

#17116 Clean up usage of `static` keyword
  src/app/application.cpp
  src/app/application.h
  src/app/signalhandler.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/statistics.cpp
  src/base/rss/rss_item.cpp
  src/base/torrentfileguard.cpp
  src/base/torrentfileguard.h
  src/base/utils/misc.cpp
  src/gui/mainwindow.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
  src/gui/torrentcontentmodel.cpp
  src/gui/torrentcontentmodel.h
  src/gui/transferlistdelegate.cpp
  src/gui/transferlistdelegate.h
  src/gui/transferlistmodel.cpp
  src/gui/transferlistmodel.h
  src/gui/uithememanager.cpp
Labels: Code cleanup

#17126 Fix DHT/PeX/LSD status when it is globally disabled
  src/gui/properties/trackerlistwidget.cpp
Labels: GUI

#17133 Don't decompress the reply data for Qt 6.3
  src/base/net/downloadhandlerimpl.cpp
Labels: Backport

#17130 Avoid redundant checks of category names
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrentimpl.cpp
Labels: Core, Code cleanup
