Repository qbittorrent/qBittorrent, pull requests merged in 2022-02, with the labels that each got.

#16336 Fix crash when shutting down and clicked on system tray icon (backport)
  src/gui/mainwindow.cpp
Labels: Backport

#16340 Backport changes to v4.4.x branch
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.ui
Labels: Backport

#16329 Optimize handleFileCompletedAlert
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#16330 Allow to use Category paths in "Manual" mode
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrentimpl.cpp
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.ui
  src/webui/api/appcontroller.cpp
  src/webui/webapplication.h
Labels: Core

#16383 Improve tracker status handling
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/gui/mainwindow.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
Labels: Performance, GUI, Core

#16408 Use QVarLengthArray whenever applicable
  src/base/bittorrent/ltqbitarray.cpp
  src/base/path.cpp
  src/base/path.h
  src/webui/www/private/css/Window.css
Labels: Code cleanup

#16411 Correctly register PathList alias
  src/base/path.cpp
Labels: Hotfix, Core

#16425 Cache file priorities
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#16436 Remove hack for outdated IE 6 browser (backport)
  src/webui/www/private/css/Window.css
Labels: Backport

#16428 Improve Path constructor
  src/base/bittorrent/ltqbitarray.cpp
  src/base/path.cpp
Labels: Hotfix, Core

#16452 Try to recover missing categories (backport to v4.4.x branch)
  src/base/bittorrent/session.cpp
Labels: Core, Backport

#16430 Try to recover missing categories
  src/base/bittorrent/session.cpp
Labels: Core

#16432 Fix UI crash when torrent is in non-existent category.
  src/webui/www/private/scripts/client.js
Labels: WebUI

#16448 Add literal operator to efficiently construct QString in Qt5
  src/base/global.h
  src/base/settingsstorage.cpp
Labels: Core

#16455 Update installer translations for "Spanish" and "Spanish International"
  dist/windows/installer-translations/spanish.nsi
  dist/windows/installer-translations/spanishinternational.nsi
Labels: NSIS

#16444 Improve performance of checking path extension
  src/base/bittorrent/customstorage.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/path.cpp
  src/base/path.h
  src/gui/uithememanager.cpp
Labels: Performance, Core

#16484 GHA CI: exclude checking for GUI i18n files
  .pre-commit-config.yaml
Labels: CI

#16460 Use std::optional to represent "any value" filters
  src/base/torrentfilter.cpp
  src/base/torrentfilter.h
  src/webui/api/torrentscontroller.cpp
Labels: Code cleanup

#16437 Unify log messages format
  src/base/bittorrent/portforwarderimpl.cpp
  src/base/bittorrent/session.cpp
Labels: Core

#16483 Convert to QString literals
  src/base/global.h
  src/base/preferences.cpp
Labels: Code cleanup

#16511 GHA CI: cancel outdated in-progress workflow runs
  .github/workflows/ci_file_health.yaml
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_webui.yaml
  .github/workflows/ci_windows.yaml
Labels: CI

#16522 Enable changing "mixed" priority from the dropdown
  src/gui/properties/proplistdelegate.cpp
Labels: GUI

#16527 Enable browsing to shortcut folders
  src/gui/fspathedit.cpp
Labels: GUI

#16526 Rename content tab "Size" column to "Total Size"
  src/gui/torrentcontentmodel.cpp
  src/webui/www/private/scripts/dynamicTable.js
Labels: WebUI, GUI

#16532 GHA CI: Update "WebUI" `setup-node` action to `v3`
  .github/workflows/ci_webui.yaml
Labels: CI

#16539 GHA CI: install boost library manually
  .github/workflows/ci_macos.yaml
Labels: CI
