Repository qbittorrent/qBittorrent, pull requests merged in 2022-07, with the labels that each got.

#17281 Fix filename not populated correctly
  src/base/path.cpp
  src/gui/torrentcreatordialog.cpp
Labels: GUI

#17278 Raise priority of the main "event loop" thread
  src/app/application.cpp
  src/app/application.h
Labels: OS: Windows, Core

#17305 Fix "Open destination folder" on macOS
  src/gui/macutilities.mm
  src/gui/transferlistwidget.cpp
Labels: OS: macOS

#17290 Try to recover missing tags
  src/base/bittorrent/session.cpp
Labels: Core

#17292 Remove option of using icons from system theme
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.ui
  src/gui/uithememanager.cpp
  src/gui/uithememanager.h
Labels: Look and feel, GUI

#17308 Make working set limit available only on libtorrent 2.0.x builds
  src/app/application.cpp
  src/app/application.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
Labels: Backport

#17311 Work around application stuttering on Windows
  src/app/application.cpp
  src/app/application.h
  src/app/upgrade.cpp
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/base/interfaces/iapplication.h
  src/gui/advancedsettings.cpp
Labels: Core, Code cleanup

#17317 Fix various typos
  dist/docker/Readme.md
  src/gui/CMakeLists.txt
  src/gui/search/searchwidget.cpp
  src/gui/torrentoptionsdialog.cpp
  src/gui/transferlistwidget.cpp
  src/webui/api/synccontroller.cpp
  src/webui/api/torrentscontroller.cpp
Labels: Code cleanup

#17333 Revise classes startup sequence
  src/app/application.cpp
  src/base/http/connection.cpp
  src/base/net/dnsupdater.cpp
  src/base/net/geoipmanager.cpp
  src/base/net/smtp.cpp
  src/base/settingsstorage.cpp
  src/gui/mainwindow.cpp
  src/webui/webui.cpp
Labels: Core, Code cleanup

#17338 Add support for unit testing
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_windows.yaml
  CMakeLists.txt
  cmake/Modules/CheckPackages.cmake
  cmake/Modules/CommonConfig.cmake
  cmake/Modules/MacroQbtCommonConfig.cmake
  src/CMakeLists.txt
  src/gui/CMakeLists.txt
  test/CMakeLists.txt
  test/Readme.md
  test/testutilsgzip.cpp
Labels: Build system, Unit test

#17341 Revise behavior of initializing checkboxes
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
Labels: GUI

#17329 Show remote access info after it is available
  src/app/application.cpp
Labels: Core

#17342 Stop installing app icon in pixmaps location
  unixconf.pri
Labels: OS: Linux, Build system

#17354 Refactor SettingsStorage implementation
  src/base/bittorrent/statistics.cpp
  src/base/profile.cpp
  src/base/profile.h
  src/base/profile_p.cpp
  src/base/profile_p.h
  src/base/rss/rss_autodownloader.cpp
  src/base/settingsstorage.cpp
  src/base/settingsstorage.h
Labels: Core, Code cleanup

#17362 Correctly remove incomplete settings file
  src/base/settingsstorage.cpp
Labels: Core

#17347 Remove meaningless checking for nullptr
  src/base/rss/rss_autodownloader.cpp
Labels: Code cleanup

#17319 Clean up WebUI preferences
  src/webui/www/private/views/preferences.html
Labels: WebUI, Code cleanup

#17359 Add testing for various classes
  test/CMakeLists.txt
  test/testalgorithm.cpp
  test/testorderedset.cpp
  test/testutilscompare.cpp
Labels: Unit test

#17363 Add workaround for payload upload/download rate
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#17376 Properly release settings class before further operations
  src/base/settingsstorage.cpp
Labels: Hotfix, Core

#17367 Split the OS cache settings into Disk IO read/write modes
  CMakeLists.txt
  INSTALL
  configure
  configure.ac
  src/base/bittorrent/session.cpp
  src/base/bittorrent/session.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: Core

#17385 Update libtorrent to 2.0.7 & 1.2.17 in GHA CI
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_windows.yaml
  .github/workflows/coverity-scan.yml
Labels: CI

#16713 Add refresh interval settings to WebUI
  src/gui/advancedsettings.cpp
  src/webui/api/appcontroller.cpp
  src/webui/www/private/views/preferences.html
Labels: WebUI, GUI

#17391 Don't show validation result dialog on every key input
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
Labels: GUI

#17396 Raise minimum libtorrent version to 2.0.7
  CMakeLists.txt
  INSTALL
  configure
  configure.ac
Labels: Build system

#17400 Prevent tray menu from being accessed after destruction
  src/app/application.cpp
  src/gui/mainwindow.cpp
Labels: Hotfix, Core, Code cleanup

#17407 Fix "Add torrent dialog" spill-over on smaller screens
  src/gui/addnewtorrentdialog.ui
  src/gui/properties/propertieswidget.cpp
Labels: GUI

#17392 Fix path validator
  src/gui/fspathedit.cpp
  src/gui/fspathedit.h
  src/gui/fspathedit_p.cpp
  src/gui/fspathedit_p.h
Labels: GUI

#17412 Improve free disk space reporting
  src/base/path.cpp
  src/base/path.h
  src/base/utils/fs.cpp
  src/gui/addnewtorrentdialog.cpp
  src/webui/webapplication.cpp
Labels: GUI, Core

#17416 Split code to smaller functions
  src/gui/fspathedit.cpp
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/torrentcontentmodel.cpp
Labels: GUI, Code cleanup

#17432 Fix peer count issue when tracker responds with zero figure
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#17438 Fix reply data can't be decompressed correctly
  src/base/net/downloadhandlerimpl.cpp
  src/base/net/downloadmanager.cpp
Labels: Network

#17446 Don't merge trackers by default
  src/base/bittorrent/session.cpp
  src/gui/addnewtorrentdialog.cpp
Labels: GUI, Core

#17453 Fix empty string parameter was omitted
  src/app/application.cpp
  src/app/cmdoptions.cpp
  src/base/utils/string.cpp
  src/base/utils/string.h
  test/CMakeLists.txt
  test/testutilsstring.cpp
Labels: Core

#17459 Backport to v4_4_x
  src/base/net/downloadhandlerimpl.cpp
  src/base/net/downloadmanager.cpp
Labels: Backport

#17366 Rename Icons according to the actions
  src/gui/categoryfilterwidget.cpp
  src/gui/cookiesdialog.cpp
  src/gui/mainwindow.cpp
  src/gui/optionsdialog.cpp
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/proptabbar.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/rss/feedlistwidget.cpp
  src/gui/rss/rsswidget.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/statusbar.cpp
  src/gui/tagfilterwidget.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistmodel.cpp
  src/gui/transferlistwidget.cpp
  src/icons/application-rss.svg
  src/icons/application-url.svg
  src/icons/browser-cookies.svg
  src/icons/chart-line.svg
  src/icons/directory.svg
  src/icons/download.svg
  src/icons/icons.qrc
  src/icons/mail-inbox.svg
  src/icons/peers-add.svg
  src/icons/peers-remove.svg
  src/icons/peers.svg
  src/icons/preferences-advanced.svg
  src/icons/preferences-bittorrent.svg
  src/icons/preferences-webui.svg
  src/icons/torrent-magnet.svg
  src/icons/torrent-start-forced.svg
  src/icons/torrent-start.svg
  src/icons/torrent-stop.svg
  src/icons/upload.svg
  src/webui/www/private/index.html
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/views/filters.html
  src/webui/www/private/views/rss.html
  src/webui/www/private/views/search.html
Labels: Code cleanup

#17454 When duplicate torrent is added set metadata to existing one
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/gui/addnewtorrentdialog.cpp
Labels: Core
