Repository qbittorrent/qBittorrent, pull requests merged in 2022-01, with the labels that each got.

#15911 Replace Qt functions with std counterparts
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/rss/rss_feed.cpp
  src/gui/addnewtorrentdialog.cpp
  src/gui/properties/downloadedpiecesbar.cpp
  src/gui/properties/pieceavailabilitybar.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/rss/automatedrssdownloader.h
  src/gui/search/searchwidget.cpp
  src/gui/speedlimitdialog.cpp
  src/gui/torrentoptionsdialog.cpp
Labels: Code cleanup

#15888 Support folder based Themes
  src/gui/optionsdialog.cpp
  src/gui/uithememanager.cpp
  src/gui/uithememanager.h
Labels: GUI

#15922 Correctly concatenate path components
  src/app/application.cpp
  src/app/upgrade.cpp
  src/base/bittorrent/session.cpp
  src/base/net/geoipmanager.cpp
  src/base/profile_p.cpp
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_session.cpp
  src/base/search/searchpluginmanager.cpp
Labels: Hotfix, Core

#15923 Misc fixes before v4.4.0
  dist/mac/Info.plist
  dist/windows/options.nsi
  src/base/bittorrent/torrentcontentlayout.cpp
  src/gui/aboutdialog.cpp
  src/qbittorrent.rc
  src/webui/www/private/views/about.html
Labels: Hotfix

#15926 Correct the order of the migrated settings' mappings
  src/app/upgrade.cpp
Labels: Hotfix

#13601 Fix bug in seeding time limit for partial torrents
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/gui/properties/propertieswidget.cpp
  src/gui/transferlistmodel.cpp
  src/webui/api/serialize/serialize_torrent.cpp
  src/webui/api/torrentscontroller.cpp
Labels: Core

#15947 Remove TODO and NEWS files
  .gitattributes
  NEWS
  TODO
  configure.ac
Labels: Project management

#15948 Move new line character out of translation string
  src/app/application.cpp
Labels: Translation

#15920 Handle .!qB extension behind the scenes
  src/base/bittorrent/abstractfilestorage.cpp
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/base/utils/fs.cpp
  src/gui/previewselectdialog.cpp
  src/gui/torrentcontentmodelfile.cpp
  src/gui/torrentcontentmodelfolder.cpp
  src/gui/transferlistwidget.cpp
  src/webui/api/torrentscontroller.cpp
  src/webui/www/private/scripts/filesystem.js
Labels: Core, Code cleanup

#15974 Move new line character out of translation string (backport)
  src/app/application.cpp
Labels: Backport

#15988 WebAPI: fix wrong key used for categories
  src/webui/api/synccontroller.cpp
  src/webui/api/torrentscontroller.cpp
  src/webui/webapplication.h
Labels: WebAPI

#15996 Mark as single window app in .desktop file
  dist/unix/org.qbittorrent.qBittorrent.desktop
Labels: OS: Linux

#16020 WebAPI: fix wrong key used for categories (backport)
  src/webui/api/synccontroller.cpp
  src/webui/api/torrentscontroller.cpp
  src/webui/webapplication.h
Labels: Backport

#16004 Correctly track the root folder name change
  src/base/bittorrent/session.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentinfo.cpp
  src/base/bittorrent/torrentinfo.h
Labels: Hotfix, Core

#16005 Correctly handle Auto TMM in Torrent Files Watcher
  src/base/torrentfileswatcher.cpp
Labels: Watched folders

#16009 Don't try to move storage into its current location
  src/base/bittorrent/torrentimpl.cpp
Labels: Hotfix, Core

#16018 Keep "torrent info" alive while generating .torrent file
  src/base/bittorrent/torrentinfo.cpp
Labels: Hotfix, Core

#16036 Update default value of "Type of service for peers"
  src/base/bittorrent/session.cpp
Labels: Libtorrent

#16054 Add Qt6 version to INSTALL file
  INSTALL
Labels: Project management

#16026 Update the torrent's download path field when changing category
  src/gui/torrentoptionsdialog.cpp
Labels: GUI

#16071 Correctly handle XML parsing errors
  src/base/rss/rss_parser.cpp
Labels: RSS

#16083 GHA CI: build libtorrent with `/guard:cf` flag
  .github/workflows/ci_windows.yaml
Labels: CI

#16016 Restore context menu actions
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
Labels: GUI

#16084 Correctly handle XML parsing errors
  src/base/rss/rss_parser.cpp
Labels: Backport

#16086 Correctly concatenate paths
  src/base/bittorrent/torrentimpl.cpp
Labels: Hotfix, Core

#16085 Handle missing torrent alerts
  src/base/bittorrent/session.cpp
Labels: Core

#16099 Revise error message
  conf.pri.windows
  configure
  configure.ac
  src/base/bittorrent/torrentimpl.cpp
Labels: Core, Build system

#16121 Correctly handle received metadata
  src/base/bittorrent/nativetorrentextension.cpp
Labels: Core

#16158 Don't start separate event loop for QFileDialog
  src/gui/transferlistwidget.cpp
Labels: GUI, Qt6 compat

#16172 Fix wrong closing brace position
  src/gui/transferlistwidget.cpp
Labels: Hotfix

#16215 Backport changes to v4.4 branch
  src/gui/transferlistwidget.cpp
Labels: Backport

#16167 Add "Auto resize columns" functionality
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.h
  src/gui/categoryfilterwidget.cpp
  src/gui/categoryfilterwidget.h
  src/gui/executionlogwidget.cpp
  src/gui/executionlogwidget.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/previewselectdialog.cpp
  src/gui/previewselectdialog.h
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/peerlistwidget.h
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/propertieswidget.h
  src/gui/properties/trackerlistwidget.cpp
  src/gui/properties/trackerlistwidget.h
  src/gui/rss/rsswidget.cpp
  src/gui/rss/rsswidget.h
  src/gui/search/pluginselectdialog.cpp
  src/gui/search/pluginselectdialog.h
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
  src/gui/tagfilterwidget.cpp
  src/gui/tagfilterwidget.h
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistfilterswidget.h
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
Labels: GUI

#16183 Improve Torrent content tree structure creation
  src/gui/torrentcontentmodel.cpp
  src/gui/torrentcontentmodelfolder.cpp
  src/gui/torrentcontentmodelfolder.h
Labels: GUI

#16238 Cache pieces info
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#16247 Speed up piece relevance calculation
  src/base/bittorrent/peerinfo.cpp
  src/base/bittorrent/peerinfo.h
Labels: Performance

#16237 Store hybrid torrents using legacy filenames
  src/base/bittorrent/infohash.cpp
  src/base/bittorrent/infohash.h
  src/base/bittorrent/session.cpp
  src/base/digest32.h
Labels: Core

#16241 Add confirmation for enabling Auto TMM from context menu
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
Labels: GUI

#16151 Manually specify UIC headers in CMake
  src/CMakeLists.txt
  src/app/CMakeLists.txt
  src/gui/CMakeLists.txt
Labels: Build system

#16268 Store hybrid torrents using "torrent ID" as basename
  src/base/bittorrent/infohash.cpp
  src/base/bittorrent/infohash.h
  src/base/bittorrent/session.cpp
  src/base/digest32.h
Labels: Core

#16267 Change torrent moving state when it is cancelled
  src/base/bittorrent/session.cpp
Labels: Core

#16252 Open correct directory when clicked on Browse button
  src/gui/fspathedit.cpp
  src/gui/fspathedit.h
Labels: GUI

#16256 Speed up bitfields conversion
  src/base/CMakeLists.txt
  src/base/base.pri
  src/base/bittorrent/ltqbitarray.cpp
  src/base/bittorrent/ltqbitarray.h
  src/base/bittorrent/peerinfo.cpp
  src/base/bittorrent/torrentimpl.cpp
Labels: Performance

#16318 Allow to open incomplete files from content view
  src/gui/properties/propertieswidget.cpp
Labels: GUI, Hotfix

#16317 Don't rename file because of difference in path separator
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#16298 Improve tracker error handling
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#16328 Fix crash when shutting down and clicked on system tray icon
  src/gui/mainwindow.cpp
Labels: GUI

#16333 Add Select All/None buttons in new torrent dialog
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.ui
Labels: GUI
