Repository qbittorrent/qBittorrent, pull requests merged in 2022-12, with the labels that each got.

#18118 WebAPI: return paths using platform-independent separator format
  src/webui/api/torrentscontroller.cpp
Labels: Hotfix, WebAPI

#18094 Revise text color for completed status
  src/gui/color.h
  src/gui/transferlistmodel.cpp
Labels: Look and feel, GUI

#18173 Correctly load folder based UI theme
  src/gui/uithememanager.cpp
Labels: GUI, Hotfix

#18124 WebAPI: return paths using platform-independent separator format
  src/webui/api/torrentscontroller.cpp
Labels: Hotfix, WebAPI, Backport

#18179 Correctly load folder based UI theme
  src/gui/uithememanager.cpp
Labels: GUI, Backport

#18146 Use identical conversions of tracker names
  src/base/bittorrent/torrentimpl.cpp
Labels: Hotfix, Core

#18154 WebUI: Make rename file dialog resizable
  src/webui/www/private/rename_file.html
  src/webui/www/private/scripts/prop-files.js
Labels: WebUI

#18199 Remove docker information
  dist/docker/.env
  dist/docker/Dockerfile
  dist/docker/Readme.md
  dist/docker/docker-compose.yml
  dist/docker/entrypoint.sh
Labels: Project management

#18141 Add "Rename rule" button to RSS Downloader
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/rss/automatedrssdownloader.h
  src/gui/rss/automatedrssdownloader.ui
Labels: RSS, GUI

#18200 CI: Build AppImage
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/helper/appimage/export_vars.sh
  .github/workflows/helper/appimage/org.qbittorrent.qBittorrent.desktop
Labels: OS: Linux, CI

#18186 Don't drop !qB extension when rename incomplete file
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Hotfix, Core

#18034 Fetch data asynchronously
  src/base/bittorrent/peerinfo.cpp
  src/base/bittorrent/peerinfo.h
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/trackerlistwidget.cpp
Labels: Core

#18258 Correctly detect drive letter in path
  src/base/path.cpp
Labels: Hotfix, Core

#18231 Don't drop !qB extension when rename incomplete file
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core, Backport

#18261 Correctly count the number of torrents in subcategories
  src/gui/categoryfiltermodel.cpp
Labels: GUI

#18251 Use "additional trackers" when metadata retrieving
  src/base/bittorrent/sessionimpl.cpp
Labels: Core

#18262 Correctly detect drive letter in path
  src/base/path.cpp
Labels: Hotfix, Core, Backport

#18259 Correctly detect whether desktop integration is active
  src/gui/desktopintegration.cpp
Labels: GUI, Hotfix

#18226 Fix icon colors inconsistencies
  src/icons/browser-cookies.svg
  src/icons/filter-stalled.svg
  src/icons/view-refresh.svg
  src/webui/www/private/images/filter-stalled.svg
  src/webui/www/private/images/view-refresh.svg
Labels: Look and feel, Hotfix

#18236 WebUI: Prevent incorrect line breaking in properties panel
  src/webui/www/private/views/properties.html
Labels: WebUI

#18240 NSIS: Update Swedish translation
  dist/windows/installer-translations/swedish.nsi
Labels: Translations, NSIS

#18279 GHA CI: Bump Windows/macOS `Boost` version to `1.81.0`
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_windows.yaml
Labels: CI

#18270 Apply correct tab order to Category options dialog
  src/gui/torrentcategorydialog.cpp
  src/gui/torrentcategorydialog.ui
Labels: GUI

#18195 Re-allow to use icons from system theme
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/categoryfiltermodel.cpp
  src/gui/categoryfilterwidget.cpp
  src/gui/executionlogwidget.cpp
  src/gui/mainwindow.cpp
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.ui
  src/gui/properties/propertieswidget.cpp
  src/gui/properties/proptabbar.cpp
  src/gui/properties/trackerlistwidget.cpp
  src/gui/properties/trackersadditiondialog.cpp
  src/gui/rss/articlelistwidget.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/rss/feedlistwidget.cpp
  src/gui/rss/rsswidget.cpp
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchwidget.cpp
  src/gui/statusbar.cpp
  src/gui/tagfiltermodel.cpp
  src/gui/tagfilterwidget.cpp
  src/gui/torrentcontentmodel.cpp
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistmodel.cpp
  src/gui/transferlistwidget.cpp
  src/gui/uithememanager.cpp
  src/gui/uithememanager.h
Labels: OS: Linux, Look and feel, GUI

#18227 WebAPI: Expose "IS PRIVATE" flag
  src/webui/api/torrentscontroller.cpp
Labels: WebAPI

#18218 WebAPI: Add "name" and "hash" fields to "torrents/properties" result
  src/webui/api/torrentscontroller.cpp
Labels: WebAPI

#17994 Unify the way to generate the language list in WebUI and GUI
  src/base/utils/misc.cpp
  src/base/utils/misc.h
  src/gui/optionsdialog.cpp
  src/webui/webapplication.cpp
  src/webui/www/private/views/preferences.html
Labels: WebUI, GUI

#18286 WebUI: change order of accepted types of file input
  src/webui/www/private/upload.html
Labels: WebUI
