Repository qbittorrent/qBittorrent, pull requests merged in 2023-02, with the labels that each got.

#18503 Don't increase limits when prefetching metadata for added magnets
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
Labels: Core

#18469 Improve command line parameters dispatching
  src/app/application.cpp
  src/app/application.h
  src/app/cmdoptions.cpp
  src/app/cmdoptions.h
  src/app/main.cpp
Labels: Code cleanup

#18516 Revert changes of conflict resolution strategy on automatic move
  src/base/bittorrent/torrentimpl.cpp
Labels: Hotfix, Core

#18517 Revert changes of conflict resolution strategy on automatic move
  src/base/bittorrent/torrentimpl.cpp
Labels: Core, Backport

#18500 Harden the SSL/TLS web server
  src/base/http/server.cpp
Labels: Security, WebUI, WebAPI

#18435 Allow to use another icons in dark mode
  src/gui/log/logmodel.cpp
  src/gui/rss/articlelistwidget.cpp
  src/gui/transferlistmodel.cpp
  src/gui/uithememanager.cpp
  src/gui/uithememanager.h
  src/gui/utils.cpp
  src/webui/webapplication.cpp
Labels: GUI, Code cleanup

#18518 Allow to add new torrents to queue top
  src/base/bittorrent/addtorrentparams.h
  src/base/bittorrent/loadtorrentparams.h
  src/base/bittorrent/session.h
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
  src/base/torrentfileswatcher.cpp
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.ui
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.ui
  src/gui/watchedfolderoptionsdialog.cpp
  src/gui/watchedfolderoptionsdialog.ui
  src/webui/api/appcontroller.cpp
  src/webui/api/torrentscontroller.cpp
Labels: GUI, Core, WebAPI

#18394 WebAPI: Improve "sync/maindata" performance
  src/base/bittorrent/session.h
  src/base/bittorrent/sessionimpl.cpp
  src/webui/api/synccontroller.cpp
  src/webui/api/synccontroller.h
Labels: Performance, WebAPI

#18506 WebUI: Add filelog settings
  src/webui/api/appcontroller.cpp
  src/webui/webapplication.h
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/preferencesToolbar.html
Labels: WebUI, WebAPI

#18452 Backports for v4_5_x part 2
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_windows.yaml
  .github/workflows/helper/appimage/export_vars.sh
  .github/workflows/helper/appimage/org.qbittorrent.qBittorrent.desktop
  dist/docker/.env
  dist/docker/Dockerfile
  dist/docker/Readme.md
  dist/docker/docker-compose.yml
  dist/docker/entrypoint.sh
  dist/windows/installer-translations/lithuanian.nsi
  dist/windows/installer-translations/swedish.nsi
  dist/windows/installer.nsi
  src/app/application.cpp
  src/app/main.cpp
  src/app/upgrade.cpp
  src/app/upgrade.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/transferlistfilterswidget.cpp
  src/gui/transferlistmodel.cpp
  src/icons/icons.qrc
  src/icons/stopped.svg
  src/icons/torrent-stop.svg
  src/webui/api/torrentscontroller.cpp
  src/webui/www/private/images/stopped.svg
  src/webui/www/private/images/torrent-stop.svg
  src/webui/www/private/rename_file.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/views/filters.html
  src/webui/www/private/views/properties.html
  src/webui/www/private/views/search.html
  src/webui/www/translations/webui_hr.ts
  src/webui/www/webui.qrc
Labels: Backport

#18555 Prevent precise timers from being used when unnecessary
  src/app/main.cpp
  src/base/bittorrent/sessionimpl.cpp
  src/base/torrentfileswatcher.cpp
  src/webui/api/appcontroller.cpp
Labels: Core

#18552 NSIS: Update Turkish translation
  dist/windows/installer-translations/turkish.nsi
Labels: Translations, NSIS

#18554 Migrate away from unsafe function
  src/webui/www/private/scripts/client.js
Labels: WebUI

#18568 NSIS: Add Uzbek translation
  dist/windows/installer-translations/uzbek.nsi
Labels: Translations, NSIS

#18572 Access some more data in a non-blocking manner
  src/base/bittorrent/extensiondata.h
  src/base/bittorrent/nativesessionextension.cpp
  src/base/bittorrent/nativetorrentextension.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#18580 Rename isSeed to isFinished to correctly represent its meaning
  src/base/bittorrent/bencoderesumedatastorage.cpp
  src/base/bittorrent/dbresumedatastorage.cpp
  src/base/bittorrent/loadtorrentparams.h
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/torrent.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/gui/mainwindow.cpp
  src/gui/properties/propertieswidget.cpp
  src/gui/transferlistwidget.cpp
  src/webui/api/torrentscontroller.cpp
Labels: Code cleanup

#18576 Add shortcut for "Ban peer permanently" function
  src/gui/properties/peerlistwidget.cpp
Labels: GUI

#18579 Update the cached state once recheck is started
  src/base/bittorrent/torrentimpl.cpp
Labels: Hotfix, Core

#18544 Show filtered port numbers in logs
  src/base/bittorrent/sessionimpl.cpp
Labels: Core

#18287 WebUI: add multi-file renaming
  src/webui/www/private/css/style.css
  src/webui/www/private/index.html
  src/webui/www/private/rename_files.html
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/file-tree.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/scripts/preferences.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/scripts/rename-files.js
  src/webui/www/private/views/transferlist.html
  src/webui/www/webui.qrc
Labels: WebUI

#18596 GHA CI: Add missing dependencies
  .github/workflows/ci_ubuntu.yaml
Labels: CI

#18567 Backport changes to v4.5.x branch
  .github/workflows/ci_file_health.yaml
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_webui.yaml
  .github/workflows/ci_windows.yaml
  .github/workflows/coverity-scan.yml
  .github/workflows/stale_bot.yaml
  dist/windows/installer-translations/turkish.nsi
  dist/windows/installer-translations/uzbek.nsi
  src/app/main.cpp
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/http/server.cpp
  src/base/torrentfileswatcher.cpp
  src/webui/api/appcontroller.cpp
  src/webui/www/private/scripts/client.js
Labels: Backport

#18597 Perform own tracking of files progress
  src/base/bittorrent/torrentcontenthandler.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/torrentcontentmodel.cpp
Labels: Core

#18619 Prevent RSS folder from being moved into itself
  src/base/rss/rss_session.cpp
  src/gui/rss/feedlistwidget.cpp
Labels: RSS

#18613 WebAPI: Allow to set read-only directory as torrent location
  src/webui/api/torrentscontroller.cpp
Labels: WebAPI

#18627 Backport changes to v4.5.x branch
  src/base/rss/rss_session.cpp
  src/gui/rss/feedlistwidget.cpp
  src/webui/api/torrentscontroller.cpp
  src/webui/webapplication.cpp
Labels: Backport

#18623 Index torrents table by queue position
  src/base/bittorrent/dbresumedatastorage.cpp
Labels: Core
