Repository qbittorrent/qBittorrent, pull requests merged in 2023-08, with the labels that each got.

#19390 Remove unused conditional
  src/base/utils/misc.cpp
  src/gui/properties/speedplotview.cpp
Labels: Code cleanup

#19397 Don't use variable after it is moved
  src/base/bittorrent/torrentdescriptor.cpp
Labels: Hotfix

#19396 GHA CI: specify a category for CodeQL analysis
  .github/workflows/ci_ubuntu.yaml
  cmake/Modules/CommonConfig.cmake
  src/gui/addnewtorrentdialog.cpp
Labels: Code cleanup, CI

#19024 WebUI: Use setProperty() for selecting an option
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/views/log.html
  src/webui/www/private/views/preferences.html
Labels: WebUI, Stale

#19403 Ensure file name is valid when exporting torrents
  src/gui/transferlistwidget.cpp
Labels: GUI

#19404 Remove column span
  src/gui/properties/propertieswidget.ui
Labels: GUI

#19394 Raise minimum supported Qt version to 6.5
  CMakeLists.txt
  INSTALL
  src/base/global.h
  src/base/utils/gzip.cpp
  src/base/utils/io.cpp
Labels: Project management, Code cleanup

#19419 Disable using Qt functions deprecated up to Qt 6.5
  cmake/Modules/CommonConfig.cmake
  src/base/bittorrent/sessionimpl.cpp
  src/base/http/server.cpp
Labels: Code cleanup

#19424 Replace template conditionals with C++20 `requires` clause
  src/base/algorithm.h
  src/base/orderedset.h
  src/base/settingsstorage.h
  src/base/utils/string.h
  src/base/utils/version.h
  test/testalgorithm.cpp
Labels: Code cleanup

#19426 Remove unused parameter in Utils::Gui::scaledPixmap()
  src/gui/aboutdialog.cpp
  src/gui/utils.cpp
  src/gui/utils.h
Labels: Code cleanup

#19428 Bump boost requirement to 1.76
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  CMakeLists.txt
  INSTALL
Labels: Project management, CI

#19430 Move to separate headers
  CODING_GUIDELINES.md
  src/app/application.h
  src/app/applicationinstancemanager.cpp
  src/app/main.cpp
  src/app/qtlocalpeer/qtlocalpeer.cpp
  src/app/signalhandler.cpp
  src/app/upgrade.cpp
  src/base/applicationcomponent.h
  src/base/bittorrent/abstractfilestorage.h
  src/base/bittorrent/cachestatus.h
  src/base/bittorrent/infohash.h
  src/base/bittorrent/peeraddress.h
  src/base/bittorrent/sessionstatus.h
  src/base/bittorrent/speedmonitor.h
  src/base/bittorrent/torrent.h
  src/base/bittorrent/tracker.h
  src/base/bittorrent/trackerentry.h
  src/base/digest32.h
  src/base/global.h
  src/base/indexrange.h
  src/base/interfaces/iapplication.h
  src/base/net/downloadmanager.h
  src/base/net/geoipdatabase.h
  src/base/path.h
  src/base/preferences.h
  src/base/torrentfileswatcher.cpp
  src/base/utils/compare.h
  src/base/utils/gzip.cpp
  src/base/utils/misc.h
  src/base/utils/random.cpp
  src/gui/log/loglistview.cpp
  src/gui/mainwindow.cpp
  src/gui/powermanagement/powermanagement.cpp
  src/gui/programupdater.cpp
  src/gui/properties/peerlistwidget.cpp
  src/gui/rss/automatedrssdownloader.cpp
  src/gui/search/searchwidget.cpp
  src/gui/uithemecommon.h
  src/gui/uithememanager.h
  src/gui/uithemesource.h
  src/gui/utils.cpp
  test/testalgorithm.cpp
  test/testbittorrenttrackerentry.cpp
  test/testglobal.cpp
  test/testorderedset.cpp
  test/testpath.cpp
  test/testutilsbytearray.cpp
  test/testutilscompare.cpp
  test/testutilsgzip.cpp
  test/testutilsio.cpp
  test/testutilsstring.cpp
  test/testutilsversion.cpp
Labels: Code cleanup

#19437 Specify charset and end_of_line in .editorconfig
  .editorconfig
Labels: Project management

#19427 Remove unused include
  CMakeLists.txt
  src/base/bittorrent/trackerentry.h
Labels: Code cleanup

#19445 Replace Q_UNLIKELY with [[unlikely]] attribute
  src/base/bittorrent/sessionimpl.cpp
  src/gui/addnewtorrentdialog.cpp
Labels: Code cleanup

#19440 Specify interface requirements as an C++ concept
  src/base/CMakeLists.txt
  src/base/concepts/stringable.h
  src/base/path.cpp
  src/base/path.h
  src/base/settingsstorage.h
  src/base/utils/version.cpp
  src/base/utils/version.h
  test/CMakeLists.txt
  test/testconceptsstringable.cpp
  test/testutilsversion.cpp
Labels: Code cleanup

#19448 Correctly load colors from custom themes
  src/gui/uithemesource.cpp
  src/gui/uithemesource.h
Labels: GUI, Hotfix

#19444 Fix overwriting feeds.json with an incomplete load of it
  src/base/rss/rss_session.cpp
  src/base/rss/rss_session.h
Labels: RSS

#19463 Check returned Bundle ID for NULL
  src/base/preferences.cpp
Labels: OS: macOS

#19462 Display error message when unrecoverable error occured
  src/app/application.cpp
  src/app/main.cpp
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#19455 Backport changes to v4.5.x branch
  src/base/rss/rss_session.cpp
  src/base/rss/rss_session.h
Labels: Backport

#19459 Disable clang-tidy for 3rd-party code
  src/base/3rdparty/.clang-tidy
Labels: Project management

#19458 Use `using` declarations instead of `typedef`
  .clang-tidy
  CODING_GUIDELINES.md
  src/base/bittorrent/speedmonitor.h
  src/base/types.h
Labels: Code cleanup

#19355 Implement gateway for adding new torrents
  src/app/application.cpp
  src/app/application.h
  src/base/CMakeLists.txt
  src/base/addtorrentmanager.cpp
  src/base/addtorrentmanager.h
  src/base/applicationcomponent.cpp
  src/base/applicationcomponent.h
  src/base/bittorrent/infohash.cpp
  src/base/bittorrent/infohash.h
  src/base/bittorrent/session.h
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
  src/base/interfaces/iapplication.h
  src/base/preferences.cpp
  src/base/preferences.h
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_autodownloader.h
  src/gui/CMakeLists.txt
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/gui/guiaddtorrentmanager.cpp
  src/gui/guiaddtorrentmanager.h
  src/gui/guiapplicationcomponent.h
  src/gui/interfaces/iguiapplication.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.h
  src/gui/rss/rsswidget.cpp
  src/gui/rss/rsswidget.h
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchjobwidget.h
  src/gui/search/searchwidget.cpp
  src/gui/search/searchwidget.h
  src/webui/api/apicontroller.cpp
  src/webui/api/apicontroller.h
  src/webui/api/torrentscontroller.cpp
  src/webui/webapplication.cpp
  src/webui/webapplication.h
  src/webui/webui.h
Labels: Core

#19453 GHA CI: Bump Windows/macOS Boost version to 1.83.0
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_windows.yaml
  .pre-commit-config.yaml
Labels: CI

#19465 Convert Windows header names to lowercase
  CODING_GUIDELINES.md
  src/app/application.cpp
  src/app/qtlocalpeer/qtlocalpeer.cpp
  src/base/bittorrent/sessionimpl.cpp
  src/base/utils/fs.cpp
  src/base/utils/misc.cpp
  src/base/utils/misc.h
  src/base/utils/random.cpp
  src/gui/mainwindow.cpp
  src/gui/programupdater.cpp
  src/gui/torrentcontentmodel.cpp
  src/gui/utils.cpp
Labels: Code cleanup

#19471 Replace `Q_UNUSED` with `[[maybe_unused]]` attribute
  src/app/application.cpp
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/net/geoipdatabase.cpp
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_feed.cpp
  src/base/utils/misc.cpp
  src/gui/addnewtorrentdialog.cpp
  src/gui/cookiesmodel.cpp
  src/gui/desktopintegration.cpp
  src/gui/fspathedit_p.cpp
  src/gui/mainwindow.cpp
  src/gui/notifications/dbusnotifier.cpp
  src/gui/search/searchwidget.cpp
  src/gui/torrentcontentmodel.cpp
  src/gui/torrentoptionsdialog.cpp
  src/gui/transferlistfilters/categoryfilterwidget.cpp
  src/gui/transferlistfilters/tagfilterwidget.cpp
  src/gui/watchedfoldersmodel.cpp
  test/testalgorithm.cpp
Labels: Code cleanup

#19468 Improve tracker entries handling
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/base/bittorrent/trackerentry.h
  src/gui/properties/trackerlistwidget.cpp
  src/gui/properties/trackerlistwidget.h
  src/webui/api/torrentscontroller.cpp
Labels: GUI

#19493 Don't overwrite tracker entry of unrelated protocol
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#19500 Use QThreadPool for torrent creation
  src/base/CMakeLists.txt
  src/base/bittorrent/torrentcreator.cpp
  src/base/bittorrent/torrentcreator.h
  src/gui/torrentcreatordialog.cpp
  src/gui/torrentcreatordialog.h
Labels: Core

#19495 Open "Save path" if torrent has no metadata
  src/gui/transferlistwidget.cpp
Labels: GUI

#19507 Use atomic primitives from standard library
  src/app/application.cpp
  src/app/application.h
  src/base/bittorrent/torrentcreator.cpp
  src/base/bittorrent/torrentcreator.h
Labels: Code cleanup

#19501 Use `std::clamp()` instead of various other implementations
  src/app/application.cpp
  src/base/bittorrent/sessionimpl.cpp
  src/base/preferences.cpp
Labels: Code cleanup

#19494 Don't set parent of "Add new torrent dialog" on macOS
  src/gui/guiaddtorrentmanager.cpp
Labels: OS: macOS, GUI

#19525 Perform type conversion properly
  src/base/utils/io.cpp
Labels: Hotfix
