Repository qbittorrent/qBittorrent, pull requests merged in 2023-04, with the labels that each got.

#18792 GHA CI: add missing dll
  .github/workflows/ci_windows.yaml
Labels: CI

#18740 WebUI: Implement subcategories
  src/webui/api/appcontroller.cpp
  src/webui/api/synccontroller.cpp
  src/webui/www/private/index.html
  src/webui/www/private/newcategory.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/views/filters.html
  src/webui/www/private/views/preferences.html
Labels: WebUI, WebAPI

#18797 Implement torrent tags editing dialog
  src/base/orderedset.h
  src/gui/CMakeLists.txt
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.ui
  src/gui/flowlayout.cpp
  src/gui/flowlayout.h
  src/gui/gui.pri
  src/gui/torrenttagsdialog.cpp
  src/gui/torrenttagsdialog.h
  src/gui/torrenttagsdialog.ui
  test/testorderedset.cpp
Labels: GUI

#18652 Backport changes to v4.5.x branch
  dist/windows/installer-translations/slovak.nsi
  src/base/bittorrent/dbresumedatastorage.cpp
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/gui/optionsdialog.cpp
Labels: Backport

#18806 Expose 'socket send/receive buffer size' options
  src/base/bittorrent/session.h
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
  src/base/utils/net.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/api/appcontroller.cpp
  src/webui/webapplication.h
  src/webui/www/private/views/preferences.html
Labels: Core

#18807 Allow to edit RSS feed URL
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_autodownloader.h
  src/base/rss/rss_feed.cpp
  src/base/rss/rss_feed.h
  src/base/rss/rss_session.cpp
  src/base/rss/rss_session.h
  src/gui/rss/rsswidget.cpp
  src/gui/rss/rsswidget.h
  src/gui/rss/rsswidget.ui
  src/webui/api/rsscontroller.cpp
  src/webui/api/rsscontroller.h
  src/webui/webapplication.h
Labels: RSS

#18812 Use KiB unit for socket buffer sizes
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/webui/www/private/views/preferences.html
Labels: WebUI, GUI

#18825 Move feature macro declaration to build scripts
  cmake/Modules/CommonConfig.cmake
  configure
  configure.ac
  src/base/utils/misc.cpp
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/gui/desktopintegration.cpp
  src/gui/desktopintegration.h
  src/gui/mainwindow.cpp
  src/gui/optionsdialog.cpp
  src/gui/powermanagement/powermanagement.cpp
  src/gui/powermanagement/powermanagement.h
Labels: Code cleanup, Build system

#18844 Don't miss saving "download path" in SQLite storage
  src/base/bittorrent/dbresumedatastorage.cpp
Labels: Core

#18832 Disable UPnP for web UI by default
  src/base/preferences.cpp
Labels: WebUI

#18843 Set "SameSite=None" if CSRF Protection is disabled
  src/webui/webapplication.cpp
Labels: WebAPI

#18837 WebUI: Use workaround for IOS file picker
  src/webui/www/private/upload.html
Labels: WebUI

#18783 Inhibit system sleep while torrents are moving
  src/gui/mainwindow.cpp
Labels: Core

#18853 Work around Chrome download limit
  src/base/logger.h
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/mocha-init.js
Labels: WebUI, Code cleanup

#18857 Improve move storage handling
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
Labels: Core

#18876 Switch URLs to https
  CONTRIBUTING.md
  INSTALL
  README.md
  dist/unix/org.qbittorrent.qBittorrent.appdata.xml
  doc/qbittorrent-nox.1
  doc/qbittorrent-nox.1.md
  doc/qbittorrent.1
  doc/qbittorrent.1.md
  src/app/signalhandler.cpp
  src/base/net/dnsupdater.cpp
  src/base/search/searchpluginmanager.cpp
  src/gui/aboutdialog.cpp
  src/gui/mainwindow.cpp
  src/gui/search/pluginselectdialog.ui
  src/gui/stacktracedialog.cpp
  src/webui/www/private/index.html
  src/webui/www/private/views/about.html
  src/webui/www/private/views/searchplugins.html
Labels: Code cleanup

#18870 GHA CI: Update some dependencies
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_windows.yaml
  .github/workflows/coverity-scan.yml
Labels: CI

#18877 Clean up CI scripts
  .github/workflows/coverity-scan.yaml
  .github/workflows/helper/appimage/export_vars.sh
  .github/workflows/helper/pre-commit/check_translation_tag.py
  .github/workflows/stale_bot.yaml
  .pre-commit-config.yaml
Labels: Code cleanup, CI

#18900 Completely initialize native status on torrent creation
  src/base/bittorrent/nativetorrentextension.cpp
Labels: Core

#18901 Improve logging of running external program
  src/app/application.cpp
Labels: Core

#18879 Replace status_t with disk_status
  src/base/bittorrent/customstorage.cpp
Labels: Core
