Repository qbittorrent/qBittorrent, pull requests merged in 2024-05, with the labels that each got.

#20776 Include missing header
  src/base/utils/number.cpp
Labels: Hotfix

#20686 WebAPI: Provide "isPrivate" flag via "torrents/info" endpoint
  src/webui/api/serialize/serialize_torrent.cpp
  src/webui/api/serialize/serialize_torrent.h
Labels: WebAPI

#20757 Add ability to pause/resume entire session
  src/base/bittorrent/session.h
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentimpl.h
  src/base/preferences.cpp
  src/base/preferences.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/mainwindow.ui
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.ui
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
Labels: Core

#20727 WebUI: migrate ESLint rules
  src/webui/www/.eslintrc.json
  src/webui/www/package.json
Labels: WebUI

#20801 Update User-Agent
  src/base/net/downloadmanager.cpp
  src/searchengine/nova3/helpers.py
Labels: Search engine, Core

#20800 WebUI: migrate to ESLint v9
  src/webui/www/.eslintrc.json
  src/webui/www/eslint.config.mjs
  src/webui/www/package.json
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/misc.js
Labels: WebUI

#20788 Sanitize peer client names
  src/base/bittorrent/peerinfo.cpp
Labels: Core

#20636 Backport changes to v4.6.x branch
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  dist/unix/org.qbittorrent.qBittorrent.metainfo.xml
  src/app/application.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/torrentfilter.h
  src/gui/addnewtorrentdialog.cpp
  src/gui/fspathedit_p.cpp
  src/gui/fspathedit_p.h
  src/gui/mainwindow.cpp
  src/gui/transferlistfilters/statusfilterwidget.cpp
  src/gui/transferlistwidget.cpp
  src/gui/transferlistwidget.h
  src/webui/www/package.json
  src/webui/www/private/scripts/prop-trackers.js
Labels: Backport

#20824 WebAPI: Add a way to download .torrent file using search plugin
  src/base/search/searchdownloadhandler.cpp
  src/base/search/searchdownloadhandler.h
  src/base/search/searchhandler.cpp
  src/base/search/searchhandler.h
  src/base/search/searchpluginmanager.cpp
  src/base/search/searchpluginmanager.h
  src/gui/search/searchjobwidget.cpp
  src/gui/search/searchsortmodel.h
  src/searchengine/nova3/nova2dl.py
  src/webui/api/searchcontroller.cpp
  src/webui/api/searchcontroller.h
Labels: Search engine, WebAPI, Code cleanup

#20842 Allow to rearrange search tabs
  src/gui/search/searchwidget.ui
Labels: Search engine, GUI

#20847 Don't hide member variables when storing current speeds
  src/gui/mainwindow.cpp
Labels: Hotfix

#20763 GHA CI: don't use hardcoded path
  .github/workflows/ci_macos.yaml
Labels: CI

#20854 Revamp alerts handling
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/sessionimpl.h
Labels: Core, Code cleanup

#20848 Improve structure of AddNewTorrentDialog code
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.h
  src/gui/addnewtorrentdialog.ui
  src/gui/guiaddtorrentmanager.cpp
Labels: GUI, Code cleanup

#20864 Adjust user agent version automatically
  src/base/net/downloadmanager.cpp
  src/searchengine/nova3/__init__.py
  src/searchengine/nova3/helpers.py
Labels: Network

#20828 WebUI: enforce coding styles
  src/webui/www/eslint.config.mjs
  src/webui/www/package.json
  src/webui/www/private/addpeers.html
  src/webui/www/private/addtrackers.html
  src/webui/www/private/confirmdeletion.html
  src/webui/www/private/confirmfeeddeletion.html
  src/webui/www/private/confirmruleclear.html
  src/webui/www/private/confirmruledeletion.html
  src/webui/www/private/download.html
  src/webui/www/private/downloadlimit.html
  src/webui/www/private/edittracker.html
  src/webui/www/private/newcategory.html
  src/webui/www/private/newfeed.html
  src/webui/www/private/newfolder.html
  src/webui/www/private/newrule.html
  src/webui/www/private/newtag.html
  src/webui/www/private/rename.html
  src/webui/www/private/rename_feed.html
  src/webui/www/private/rename_file.html
  src/webui/www/private/rename_files.html
  src/webui/www/private/rename_rule.html
  src/webui/www/private/scripts/cache.js
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/download.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/file-tree.js
  src/webui/www/private/scripts/filesystem.js
  src/webui/www/private/scripts/localpreferences.js
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/scripts/piecesbar.js
  src/webui/www/private/scripts/progressbar.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/scripts/prop-general.js
  src/webui/www/private/scripts/prop-peers.js
  src/webui/www/private/scripts/prop-trackers.js
  src/webui/www/private/scripts/prop-webseeds.js
  src/webui/www/private/scripts/rename-files.js
  src/webui/www/private/scripts/search.js
  src/webui/www/private/scripts/speedslider.js
  src/webui/www/private/setlocation.html
  src/webui/www/private/shareratio.html
  src/webui/www/private/upload.html
  src/webui/www/private/uploadlimit.html
  src/webui/www/private/views/about.html
  src/webui/www/private/views/aboutToolbar.html
  src/webui/www/private/views/filters.html
  src/webui/www/private/views/installsearchplugin.html
  src/webui/www/private/views/log.html
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/preferencesToolbar.html
  src/webui/www/private/views/properties.html
  src/webui/www/private/views/rss.html
  src/webui/www/private/views/rssDownloader.html
  src/webui/www/private/views/searchplugins.html
  src/webui/www/private/views/transferlist.html
  src/webui/www/public/scripts/login.js
Labels: WebUI, Code cleanup

#20863 Avoid creating redundant temporary file list
  src/webui/api/appcontroller.cpp
Labels: Code cleanup

#20866 Increase default height of 'Share ratio limit' dialog in WebUI
  src/webui/www/private/scripts/mocha-init.js
Labels: WebUI

#20888 Simplify HTTP cookie code
  src/webui/webapplication.cpp
Labels: Code cleanup

#20890 Avoid redundant lookup
  src/gui/properties/peerlistwidget.cpp
Labels: Code cleanup
