Repository qbittorrent/qBittorrent, pull requests merged in 2024-02, with the labels that each got.

#20357 Don't use iterator after erase
  src/base/bittorrent/sessionimpl.cpp
Labels: Core

#20365 Sort languages combobox by language code
  src/base/bittorrent/bencoderesumedatastorage.cpp
  src/base/bittorrent/torrentcreator.cpp
  src/base/search/searchpluginmanager.cpp
  src/base/torrentfileswatcher.cpp
  src/base/utils/fs.cpp
  src/base/utils/misc.cpp
  src/base/utils/misc.h
  src/gui/optionsdialog.cpp
  src/gui/optionsdialog.ui
  src/webui/webapplication.cpp
Labels: GUI, Code cleanup

#20387 Link PowrProf library to qBittorrent base
  src/base/CMakeLists.txt
  src/gui/CMakeLists.txt
Labels: Hotfix

#20377 Allow WebAPI to specify filename and mime type for result data
  src/webui/api/apicontroller.cpp
  src/webui/api/apicontroller.h
  src/webui/api/torrentscontroller.cpp
  src/webui/webapplication.cpp
Labels: WebAPI

#20371 GHA CI: Bump boost dependency and revise install method
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_windows.yaml
  .github/workflows/coverity-scan.yaml
Labels: CI

#20414 Open "lock" files for the same folder only once
  src/base/asyncfilestorage.cpp
  src/base/asyncfilestorage.h
Labels: Core

#20427 Specify standards conformance mode to MSVC
  cmake/Modules/CommonConfig.cmake
Labels: Build system

#20428 Rename to WebUI
  src/webui/www/README.md
  src/webui/www/private/index.html
  src/webui/www/private/scripts/client.js
  src/webui/www/private/views/about.html
  src/webui/www/private/views/preferences.html
  src/webui/www/private/views/preferencesToolbar.html
  src/webui/www/public/index.html
Labels: WebUI

#20430 Revise cache internals
  src/webui/www/private/scripts/cache.js
Labels: WebUI

#20424 Improve received metadata handling
  src/base/bittorrent/torrentimpl.cpp
Labels: Core

#20455 GHA CI: Bump libtorrent 2 version to 2.0.10
  .github/workflows/ci_macos.yaml
  .github/workflows/ci_ubuntu.yaml
  .github/workflows/ci_windows.yaml
  .github/workflows/coverity-scan.yaml
Labels: CI

#20429 Allow to set custom suffix to window title
  src/app/application.cpp
  src/app/application.h
  src/base/interfaces/iapplication.h
  src/gui/advancedsettings.cpp
  src/gui/advancedsettings.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/webui/api/appcontroller.cpp
  src/webui/webapplication.h
  src/webui/www/private/css/style.css
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/mocha-init.js
  src/webui/www/private/views/preferences.html
Labels: WebUI, GUI

#20465 Add a small delay before processing the key input of search boxes
  src/gui/addnewtorrentdialog.cpp
  src/gui/addnewtorrentdialog.h
  src/gui/lineedit.cpp
  src/gui/lineedit.h
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/search/searchjobwidget.cpp
  src/webui/www/private/scripts/client.js
  src/webui/www/private/scripts/contextmenu.js
  src/webui/www/private/scripts/dynamicTable.js
  src/webui/www/private/scripts/misc.js
  src/webui/www/private/scripts/prop-files.js
  src/webui/www/private/views/log.html
  src/webui/www/private/views/search.html
Labels: WebUI, GUI
