Repository qbittorrent/qBittorrent, pull requests merged in 2025-10, with the labels that each got.

#23278 Allow to filter RSS by simple string
  src/gui/rss/articlelistwidget.cpp
  src/gui/rss/articlelistwidget.h
  src/gui/rss/rsswidget.cpp
  src/gui/rss/rsswidget.h
  src/webui/www/private/views/rss.html
Labels: WebUI, RSS, GUI

#23342 Utilize algorithms from `std::ranges`
  src/app/signalhandler.cpp
  src/base/bittorrent/sessionimpl.cpp
  src/base/bittorrent/torrentcreator.cpp
  src/base/bittorrent/torrentimpl.cpp
  src/base/bittorrent/torrentinfo.cpp
  src/base/http/requestparser.cpp
  src/base/http/server.cpp
  src/base/logger.cpp
  src/base/net/downloadmanager.cpp
  src/base/net/smtp.cpp
  src/base/path.cpp
  src/base/rss/feed_serializer.cpp
  src/base/rss/rss_autodownloader.cpp
  src/base/rss/rss_autodownloadrule.cpp
  src/base/rss/rss_feed.cpp
  src/base/utils/foreignapps.cpp
  src/base/utils/fs.cpp
  src/base/utils/net.cpp
  src/gui/addnewtorrentdialog.cpp
  src/gui/addtorrentparamswidget.cpp
  src/gui/banlistoptionsdialog.cpp
  src/gui/cookiesdialog.cpp
  src/gui/mainwindow.cpp
  src/gui/optionsdialog.cpp
  src/gui/properties/peerlistwidget.cpp
  src/gui/properties/pieceavailabilitybar.cpp
  src/gui/search/searchwidget.cpp
  src/gui/torrentcontentmodel.cpp
  src/gui/torrentoptionsdialog.cpp
  src/gui/transferlistfilters/categoryfiltermodel.cpp
  src/gui/transferlistfilters/tagfiltermodel.cpp
  src/gui/transferlistfilters/trackersfilterwidget.cpp
  src/gui/transferlistwidget.cpp
  src/webui/api/apicontroller.cpp
  src/webui/api/appcontroller.cpp
  src/webui/api/torrentscontroller.cpp
  src/webui/webapplication.cpp
Labels: Code cleanup

#23343 Avoid duplicate lookup
  src/base/bittorrent/sessionimpl.cpp
Labels: Core, Code cleanup

#23344 Avoid spawning another temporary event loop
  src/gui/utils.cpp
Labels: OS: Linux

#23345 WebUI: Fix path input label layout in torrent creator
  src/webui/www/private/views/createtorrent.html
Labels: WebUI
